// P-065 — Public vendor-facing PO view.
// Renders read-only PO details via a tokenized SECURITY DEFINER lookup.
// No authentication required. Expired/invalid tokens render a branded "Link expired" page.
import { useEffect, useMemo, useState } from "react";
import { createFileRoute, useParams } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { format } from "date-fns";
import { Download, Link2Off, Receipt } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { getPoByShareToken, type PublicPoView } from "@/lib/po.functions";

const TOKEN_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export const Route = createFileRoute("/po/$token")({
  head: () => ({
    meta: [
      { title: "Purchase Order — GridMind EPC" },
      {
        name: "description",
        content: "Read-only vendor view of a purchase order shared by GridMind EPC.",
      },
      { name: "robots", content: "noindex,nofollow" },
    ],
  }),
  component: PublicPoPage,
});

function fmtMoney(n: number, currency: string) {
  try {
    return new Intl.NumberFormat(undefined, {
      style: "currency",
      currency,
      maximumFractionDigits: 2,
    }).format(n);
  } catch {
    return `${currency} ${n.toFixed(2)}`;
  }
}

function PublicPoPage() {
  const { token } = useParams({ from: "/po/$token" });
  const fetchFn = useServerFn(getPoByShareToken);

  const [state, setState] = useState<
    | { kind: "loading" }
    | { kind: "ok"; po: PublicPoView }
    | { kind: "expired" }
    | { kind: "error"; message: string }
  >(() => (TOKEN_RE.test(token) ? { kind: "loading" } : { kind: "expired" }));

  useEffect(() => {
    if (!TOKEN_RE.test(token)) return;
    let cancelled = false;
    (async () => {
      try {
        const po = await fetchFn({ data: { token } });
        if (!cancelled) setState({ kind: "ok", po });
      } catch (err: unknown) {
        if (cancelled) return;
        const anyErr = err as { statusCode?: number; body?: string; message?: string };
        let status = anyErr?.statusCode;
        let code = "";
        try {
          if (anyErr?.body) {
            const parsed = JSON.parse(anyErr.body);
            code = String(parsed?.error ?? "");
            status = status ?? Number(parsed?.status);
          }
        } catch {
          // ignore
        }
        if (status === 410 || code === "share_link_expired") {
          setState({ kind: "expired" });
        } else {
          setState({
            kind: "error",
            message: anyErr?.message ?? "Could not load this purchase order.",
          });
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [token, fetchFn]);

  const brand = useMemo(() => {
    if (state.kind !== "ok") return null;
    return {
      primary: state.po.primary_color || "#1e40af",
      accent: state.po.accent_color || "#0d9488",
      footer:
        state.po.footer_text || `Shared by ${state.po.company_name} · Generated by GridMind EPC`,
    };
  }, [state]);

  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="mx-auto max-w-4xl px-6 py-10">
        {state.kind === "loading" && (
          <div className="animate-pulse space-y-4">
            <div className="h-8 w-64 rounded bg-muted" />
            <div className="h-24 rounded bg-muted" />
            <div className="h-64 rounded bg-muted" />
          </div>
        )}

        {state.kind === "expired" && <ExpiredPage />}

        {state.kind === "error" && (
          <div className="rounded-md border border-destructive/40 bg-destructive/5 p-6 text-sm text-destructive">
            {state.message}
          </div>
        )}

        {state.kind === "ok" && brand && (
          <>
            <header
              className="rounded-md p-6 text-white"
              style={{ backgroundColor: brand.primary }}
            >
              <div className="flex items-center gap-2 text-xs uppercase tracking-wide opacity-80">
                <Receipt className="h-3.5 w-3.5" /> Purchase Order
              </div>
              <div className="mt-1 flex flex-wrap items-baseline justify-between gap-4">
                <h1 className="font-display text-3xl font-bold tracking-tight">
                  {state.po.po_number}
                </h1>
                <div className="text-right">
                  <div className="text-xs uppercase tracking-wide opacity-80">Total</div>
                  <div className="font-display text-2xl font-semibold">
                    {fmtMoney(state.po.total_amount, state.po.currency_code)}
                  </div>
                </div>
              </div>
              <div className="mt-2 text-sm opacity-90">
                Issued by <span className="font-semibold">{state.po.company_name}</span>
                {state.po.vendor_name ? ` · Vendor: ${state.po.vendor_name}` : ""}
              </div>
            </header>

            <section className="mt-6 grid gap-4 md:grid-cols-2">
              <MetaCard
                title="Delivery"
                rows={[
                  ["Project", state.po.project_name ?? "—"],
                  ["Address", state.po.delivery_address ?? "—"],
                  [
                    "Required by",
                    state.po.required_by_date
                      ? format(new Date(state.po.required_by_date), "PP")
                      : "—",
                  ],
                ]}
              />
              <MetaCard
                title="Terms"
                rows={[
                  ["Payment terms", state.po.payment_terms ?? "—"],
                  ["Incoterms", state.po.incoterms ?? "—"],
                  [
                    "Issued",
                    state.po.issued_at ? format(new Date(state.po.issued_at), "PPp") : "—",
                  ],
                ]}
              />
            </section>

            <section className="mt-6 overflow-hidden rounded-md border border-border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-14">#</TableHead>
                    <TableHead>Description</TableHead>
                    <TableHead className="text-right">Qty</TableHead>
                    <TableHead>UoM</TableHead>
                    <TableHead className="text-right">Unit price</TableHead>
                    <TableHead className="text-right">Amount</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {state.po.lines.map((l) => (
                    <TableRow key={l.line_no}>
                      <TableCell className="font-mono">{l.line_no}</TableCell>
                      <TableCell className="font-medium">
                        {l.description}
                        {l.spec && <div className="text-xs text-muted-foreground">{l.spec}</div>}
                      </TableCell>
                      <TableCell className="text-right">{l.qty}</TableCell>
                      <TableCell>{l.uom}</TableCell>
                      <TableCell className="text-right">
                        {fmtMoney(l.unit_price, state.po.currency_code)}
                      </TableCell>
                      <TableCell className="text-right font-medium">
                        {fmtMoney(l.amount, state.po.currency_code)}
                      </TableCell>
                    </TableRow>
                  ))}
                  <TableRow>
                    <TableCell colSpan={5} className="text-right text-sm text-muted-foreground">
                      Subtotal
                    </TableCell>
                    <TableCell className="text-right">
                      {fmtMoney(state.po.subtotal, state.po.currency_code)}
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell colSpan={5} className="text-right text-sm text-muted-foreground">
                      Tax ({state.po.tax_pct}%)
                    </TableCell>
                    <TableCell className="text-right">
                      {fmtMoney(state.po.tax_amount, state.po.currency_code)}
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell colSpan={5} className="text-right font-semibold">
                      Total ({state.po.currency_code})
                    </TableCell>
                    <TableCell className="text-right font-semibold">
                      {fmtMoney(state.po.total_amount, state.po.currency_code)}
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </section>

            {state.po.pdf_url && (
              <div className="mt-6 flex justify-end">
                <Button asChild>
                  <a href={state.po.pdf_url} target="_blank" rel="noopener noreferrer">
                    <Download className="mr-2 h-4 w-4" /> Download branded PDF
                  </a>
                </Button>
              </div>
            )}

            <footer className="mt-10 text-center text-xs text-muted-foreground">
              {brand.footer}
            </footer>
          </>
        )}
      </div>
    </div>
  );
}

function MetaCard({ title, rows }: { title: string; rows: Array<[string, string]> }) {
  return (
    <div className="rounded-md border border-border p-4">
      <h2 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        {title}
      </h2>
      <dl className="mt-2 grid grid-cols-3 gap-y-2 text-sm">
        {rows.map(([k, v]) => (
          <div key={k} className="contents">
            <dt className="text-muted-foreground">{k}</dt>
            <dd className="col-span-2">{v}</dd>
          </div>
        ))}
      </dl>
    </div>
  );
}

function ExpiredPage() {
  return (
    <div className="mx-auto max-w-lg rounded-lg border border-border bg-muted/30 p-10 text-center">
      <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-muted">
        <Link2Off className="h-6 w-6 text-muted-foreground" />
      </div>
      <h1 className="font-display text-2xl font-semibold">Link expired</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        This purchase order link is no longer valid. Please contact the procurement team at GridMind
        EPC to request a new link.
      </p>
    </div>
  );
}
