// P-169 — Engineering study report PDF. Brand hex is allowed inside exports only.
import type { ExportTheme } from "./theme";
import {
  contentWidth,
  createDoc,
  docBody,
  docCaption,
  docH2,
  docTable,
  drawFooters,
  drawHeaderBand,
  ensureSpace,
  fmtDate,
  mm,
  numericCol,
  PAGE,
  sanitize,
} from "./theme";
import {
  inputSheetRows,
  normalizeAssumptions,
  normalizeWarnings,
  resultSections,
  sortWarnings,
} from "@/lib/ea/present";

export type EaReportApprovalStep = {
  step_order: number;
  role: string | null;
  approver: string | null;
  status: string;
  decided_at: string | null;
  comment: string | null;
};

export type EaReportPayload = {
  studyNumber: string;
  title: string;
  studyTypeLabel: string;
  status: string;
  revision: number;
  projectName: string;
  projectCode: string | null;
  standardsRef: string[];
  method: string;
  inputSheet: unknown;
  results: unknown;
  warnings: unknown;
  assumptions: unknown;
  submittedAt: string | null;
  approvedAt: string | null;
  approvalSteps: EaReportApprovalStep[];
  disclaimer: string;
  generatedAt: string;
};

const GENERATED_BY = "Generated by GridMind EPC";

/** Builds the branded study report and returns the raw PDF bytes. */
export function buildEaStudyReportPdf(payload: EaReportPayload, theme: ExportTheme): Uint8Array {
  const doc = createDoc();
  const title = `${payload.studyNumber} — ${payload.title}`;
  const subtitle = `${payload.studyTypeLabel} · Rev ${payload.revision} · ${payload.status.replace(/_/g, " ")}`;
  const pageHeader = { title, subtitle };
  let y = drawHeaderBand(doc, theme, title, subtitle);

  // Title block ------------------------------------------------------------
  y = docTable(doc, theme, {
    startY: y,
    pageHeader,
    head: [["Field", "Value"]],
    body: [
      ["Study number", sanitize(payload.studyNumber)],
      ["Title", sanitize(payload.title)],
      ["Study type", sanitize(payload.studyTypeLabel)],
      ["Revision", String(payload.revision)],
      ["Status", sanitize(payload.status.replace(/_/g, " "))],
      [
        "Project",
        sanitize(
          payload.projectCode ? `${payload.projectName} (${payload.projectCode})` : payload.projectName,
        ),
      ],
      ["Standards referenced", sanitize(payload.standardsRef.join(", ") || "—")],
      ["Generated", fmtDate(payload.generatedAt, "PPpp")],
    ],
    columnStyles: { 0: { cellWidth: mm(45), fontStyle: "bold" } },
  });

  // Input sheet ------------------------------------------------------------
  const inputs = inputSheetRows(payload.inputSheet);
  if (inputs.length > 0) {
    y = ensureSpace(doc, theme, y, mm(40), title);
    y = docH2(doc, theme, "Input sheet", y + mm(6));
    y = docTable(doc, theme, {
      startY: y,
      pageHeader,
      head: [["Parameter", "Value"]],
      body: inputs.map((r) => [sanitize(r.label), sanitize(r.value)]),
      columnStyles: { 1: numericCol },
    });
  }

  // Input grids ------------------------------------------------------------
  if (payload.inputSheet && typeof payload.inputSheet === "object") {
    for (const [key, value] of Object.entries(payload.inputSheet as Record<string, unknown>)) {
      if (!Array.isArray(value) || value.length === 0) continue;
      const rows = value.filter((v) => v && typeof v === "object" && !Array.isArray(v)) as Array<
        Record<string, unknown>
      >;
      if (rows.length !== value.length) continue;
      const columns: string[] = [];
      for (const row of rows) {
        for (const col of Object.keys(row)) if (!columns.includes(col)) columns.push(col);
      }
      y = ensureSpace(doc, theme, y, mm(35), title);
      y = docH2(doc, theme, humanize(key), y + mm(6));
      y = docTable(doc, theme, {
        startY: y,
        pageHeader,
        head: [columns.map(humanize)],
        body: rows.map((row) => columns.map((col) => sanitize(stringify(row[col])))),
      });
    }
  }

  // Assumptions ------------------------------------------------------------
  const assumptions = normalizeAssumptions(payload.assumptions);
  if (assumptions.length > 0) {
    y = ensureSpace(doc, theme, y, mm(35), title);
    y = docH2(doc, theme, "Assumptions", y + mm(6));
    y = docTable(doc, theme, {
      startY: y,
      pageHeader,
      head: [["Assumption", "Source"]],
      body: assumptions.map((a) => [sanitize(a.text), sanitize(a.source || "—")]),
    });
  }

  // Method -----------------------------------------------------------------
  if (payload.method) {
    y = ensureSpace(doc, theme, y, mm(40), title);
    y = docH2(doc, theme, "Method and formulas", y + mm(6));
    y = docBody(doc, sanitize(payload.method), y + mm(2), contentWidth(doc));
  }

  // Results ----------------------------------------------------------------
  const sections = resultSections(payload.results);
  if (sections.scalars.length > 0) {
    y = ensureSpace(doc, theme, y, mm(35), title);
    y = docH2(doc, theme, "Results", y + mm(6));
    y = docTable(doc, theme, {
      startY: y,
      pageHeader,
      head: [["Quantity", "Value"]],
      body: sections.scalars.map((r) => [sanitize(r.label), sanitize(r.value)]),
      columnStyles: { 1: numericCol },
    });
  }
  for (const table of sections.tables) {
    y = ensureSpace(doc, theme, y, mm(35), title);
    y = docH2(doc, theme, table.title, y + mm(6));
    y = docTable(doc, theme, {
      startY: y,
      pageHeader,
      head: [table.columns],
      body: table.rows.map((row) => row.map(sanitize)),
    });
  }

  // Warnings ---------------------------------------------------------------
  const warnings = sortWarnings(normalizeWarnings(payload.warnings));
  y = ensureSpace(doc, theme, y, mm(35), title);
  y = docH2(doc, theme, "Warnings", y + mm(6));
  y = docTable(doc, theme, {
    startY: y,
    pageHeader,
    head: [["Severity", "Code", "Message"]],
    body:
      warnings.length > 0
        ? warnings.map((w) => [w.severity.toUpperCase(), sanitize(w.code), sanitize(w.message)])
        : [["—", "—", "No warnings were raised by this run."]],
    columnStyles: { 0: { cellWidth: mm(22) }, 1: { cellWidth: mm(35) } },
  });

  // Approval trail ---------------------------------------------------------
  y = ensureSpace(doc, theme, y, mm(35), title);
  y = docH2(doc, theme, "Approval trail", y + mm(6));
  y = docTable(doc, theme, {
    startY: y,
    pageHeader,
    head: [["Step", "Approver", "Status", "Decided"]],
    body:
      payload.approvalSteps.length > 0
        ? payload.approvalSteps.map((s) => [
            String(s.step_order),
            sanitize(s.approver ?? s.role ?? "—"),
            sanitize(s.status.replace(/_/g, " ")),
            s.decided_at ? fmtDate(s.decided_at, "PPp") : "—",
          ])
        : [["—", "—", "not submitted", "—"]],
    columnStyles: { 0: { cellWidth: mm(15) } },
  });
  y = docCaption(
    doc,
    `Submitted ${payload.submittedAt ? fmtDate(payload.submittedAt, "PPp") : "—"} · Approved ${
      payload.approvedAt ? fmtDate(payload.approvedAt, "PPp") : "—"
    }`,
    y + mm(4),
  );

  // Disclaimer -------------------------------------------------------------
  y = ensureSpace(doc, theme, y, mm(30), title);
  y = docH2(doc, theme, "Validation status", y + mm(6));
  y = docBody(doc, sanitize(payload.disclaimer), y + mm(2), contentWidth(doc));
  docCaption(doc, GENERATED_BY, y + mm(4));

  drawFooters(doc, theme);
  const buffer = doc.output("arraybuffer") as ArrayBuffer;
  return new Uint8Array(buffer);
}

function humanize(key: string): string {
  const spaced = key
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/[_-]+/g, " ")
    .trim()
    .toLowerCase();
  return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}

function stringify(value: unknown): string {
  if (value === null || value === undefined) return "—";
  if (typeof value === "object") return JSON.stringify(value);
  return String(value);
}

export const EA_REPORT_PAGE_MARGIN = PAGE.margin;
