// P-255 — Executive portfolio PDF.
//
// PURE + HEADLESS: `buildPortfolioExecReportPdf(data)` takes a fully resolved
// PortfolioExecReportData (company_id + period → data happens server-side) and
// returns PDF bytes. No DOM, no i18n, no Supabase — so the scheduled-reports
// cron can render the identical document without a browser.
//
// The chart on page 2 is drawn as jsPDF vectors rather than rasterised from
// Recharts, for the same reason.
import type { jsPDF } from "jspdf";

import {
  CONFIDENTIALITY_NOTE,
  LANGUAGE_NOTE,
  LIVE_DATA_STAMP,
  chartSeries,
  curveTotals,
  execReportFilename,
  fmtIndex,
  monthLabel,
  perfVerdict,
  periodLabel,
  plotX,
  plotY,
  type PortfolioExecReportData,
} from "@/lib/portfolio/exec-report.rules";
import {
  EXPOSURE_DIMENSIONS,
  PUNCH_ORDER,
  SEVERITY_ORDER,
  orderedCounts,
  sortByExposure,
  totalCounts,
  trirTrend,
} from "@/lib/portfolio/exposure.rules";
import { PHASE_RAIL, railIndex } from "@/lib/portfolio/portfolio.rules";
import {
  FONT,
  NEUTRAL,
  PAGE,
  contentWidth,
  createDoc,
  createExportTheme,
  docCaption,
  docH1,
  docH2,
  docTable,
  drawBigNumbers,
  drawHeaderBand,
  fmtMoney,
  fmtNum,
  mm,
  numericCol,
  resetInk,
  sanitize,
  tint,
  type ExportTheme,
  type Rgb,
} from "@/lib/exports/theme";

const DOC_TITLE = "Portfolio Executive Report";

const money = (v: unknown, currency: string) => fmtMoney(v, currency, 0);

function utcDateTime(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return sanitize(iso);
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())} ${pad(
    d.getUTCHours(),
  )}:${pad(d.getUTCMinutes())} UTC`;
}

// ---------------------------------------------------------------------------
// Cover

function drawCover(doc: jsPDF, theme: ExportTheme, data: PortfolioExecReportData): void {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  doc.setFillColor(theme.primary[0], theme.primary[1], theme.primary[2]);
  doc.rect(0, 0, pageW, mm(70), "F");
  doc.setFillColor(theme.accent[0], theme.accent[1], theme.accent[2]);
  doc.rect(0, mm(70), pageW, 2.4, "F");

  if (theme.logoDataUrl) {
    try {
      doc.addImage(
        theme.logoDataUrl,
        /^data:image\/jpe?g/.test(theme.logoDataUrl) ? "JPEG" : "PNG",
        PAGE.margin,
        mm(22),
        mm(45),
        mm(16),
        undefined,
        "FAST",
      );
    } catch {
      /* a broken logo must never break the document */
    }
  }

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(sanitize(data.company.legalName ?? data.company.name), PAGE.margin, mm(52));

  doc.setTextColor(NEUTRAL.ink[0], NEUTRAL.ink[1], NEUTRAL.ink[2]);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.text(DOC_TITLE, PAGE.margin, mm(100));

  doc.setFont("helvetica", "normal");
  doc.setFontSize(13);
  doc.setTextColor(NEUTRAL.muted[0], NEUTRAL.muted[1], NEUTRAL.muted[2]);
  doc.text(`Reporting period: ${periodLabel(data.period)}`, PAGE.margin, mm(112));

  const rows: Array<[string, string]> = [
    ["Company", sanitize(data.company.legalName ?? data.company.name)],
    ["Projects in scope", fmtNum(data.rowCounts.projects)],
    ["Base currency", sanitize(data.baseCurrency)],
    ["Generated by", sanitize(data.generatedBy)],
    ["Generated at", utcDateTime(data.generatedAt)],
  ];
  let y = mm(132);
  rows.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(FONT.caption);
    doc.setTextColor(NEUTRAL.muted[0], NEUTRAL.muted[1], NEUTRAL.muted[2]);
    doc.text(label.toUpperCase(), PAGE.margin, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(FONT.body);
    doc.setTextColor(NEUTRAL.body[0], NEUTRAL.body[1], NEUTRAL.body[2]);
    doc.text(value, PAGE.margin + mm(45), y);
    y += mm(8);
  });

  const soft = tint(theme.primary, 0.9);
  doc.setFillColor(soft[0], soft[1], soft[2]);
  doc.rect(0, pageH - mm(46), pageW, mm(28), "F");
  doc.setFillColor(theme.accent[0], theme.accent[1], theme.accent[2]);
  doc.rect(0, pageH - mm(46), pageW, 1.2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(FONT.caption);
  doc.setTextColor(theme.primary[0], theme.primary[1], theme.primary[2]);
  doc.text(LIVE_DATA_STAMP.toUpperCase(), PAGE.margin, pageH - mm(37));
  doc.setFont("helvetica", "normal");
  doc.setTextColor(NEUTRAL.muted[0], NEUTRAL.muted[1], NEUTRAL.muted[2]);
  doc.text(CONFIDENTIALITY_NOTE, PAGE.margin, pageH - mm(30));
  doc.text(LANGUAGE_NOTE, PAGE.margin, pageH - mm(24));
  resetInk(doc);
}

// ---------------------------------------------------------------------------
// Page 1 — KPI strip

function drawKpiPage(doc: jsPDF, theme: ExportTheme, data: PortfolioExecReportData): void {
  const { kpis } = data;
  const cur = data.baseCurrency;
  const subtitle = periodLabel(data.period);
  let y = drawHeaderBand(doc, theme, DOC_TITLE, subtitle);
  y = docH1(doc, "Portfolio performance", y);

  y = drawBigNumbers(
    doc,
    theme,
    [
      {
        label: "Active projects",
        value: fmtNum(kpis.projects.by_status?.active ?? 0),
        hint: `${fmtNum(kpis.projects.total)} total`,
      },
      { label: "Contract value", value: money(kpis.contract_value, cur), hint: cur },
      {
        label: "Weighted SPI",
        value: fmtIndex(kpis.evm.spi),
        hint: perfVerdict(kpis.evm.spi),
      },
      {
        label: "Weighted CPI",
        value: fmtIndex(kpis.evm.cpi),
        hint: perfVerdict(kpis.evm.cpi),
      },
    ],
    y,
    { perRow: 4 },
  );

  y = drawBigNumbers(
    doc,
    theme,
    [
      { label: "Open AR", value: money(kpis.ar_open, cur) },
      { label: "Open AP", value: money(kpis.ap_open, cur) },
      {
        label: "Cash MTD (net)",
        value: money(Number(kpis.cash_mtd.inflow) - Number(kpis.cash_mtd.outflow), cur),
        hint: `In ${money(kpis.cash_mtd.inflow, cur)} / Out ${money(kpis.cash_mtd.outflow, cur)}`,
      },
      { label: "Projects with EVM", value: fmtNum(kpis.evm.projects_counted) },
    ],
    y + mm(2),
    { perRow: 4 },
  );

  y = docH2(doc, theme, "Weighted earned value", y + mm(6));
  y = docCaption(
    doc,
    "Portfolio indices are weighted (sum of earned value over sum of planned/actual cost), never averages of per-project ratios.",
    y,
  );
  y = docTable(doc, theme, {
    startY: y + mm(1),
    pageHeader: { title: DOC_TITLE, subtitle },
    head: [["Measure", "Amount", "Index", "Threshold verdict"]],
    body: [
      [
        "Planned value (PV)",
        money(kpis.evm.pv, cur),
        fmtIndex(kpis.evm.spi),
        `SPI — ${perfVerdict(kpis.evm.spi)}`,
      ],
      [
        "Earned value (EV)",
        money(kpis.evm.ev, cur),
        fmtIndex(kpis.evm.cpi),
        `CPI — ${perfVerdict(kpis.evm.cpi)}`,
      ],
      ["Actual cost (AC)", money(kpis.evm.ac, cur), "", ""],
      ["Budget at completion (BAC)", money(kpis.evm.bac, cur), "", ""],
    ],
    columnStyles: { 1: numericCol, 2: numericCol },
  });

  y = docH2(doc, theme, "Projects by phase", y + mm(8));
  const phaseRows = Object.entries(kpis.projects.by_phase ?? {}).sort((a, b) =>
    a[0].localeCompare(b[0]),
  );
  docTable(doc, theme, {
    startY: y,
    pageHeader: { title: DOC_TITLE, subtitle },
    head: [["Phase", "Projects"]],
    body: phaseRows.length
      ? phaseRows.map(([phase, n]) => [titleCase(phase), fmtNum(n)])
      : [["No projects in scope", "0"]],
    columnStyles: { 1: numericCol },
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(FONT.caption);
  doc.setTextColor(NEUTRAL.muted[0], NEUTRAL.muted[1], NEUTRAL.muted[2]);
  doc.text(
    "Thresholds: index >= 0.95 on track · 0.85–0.95 watch · < 0.85 behind.",
    PAGE.margin,
    doc.internal.pageSize.getHeight() - mm(24),
  );
  resetInk(doc);
}

function titleCase(s: string): string {
  return sanitize(s)
    .replace(/[_-]+/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

// ---------------------------------------------------------------------------
// Page 2 — cash curve chart + monthly table

function drawCashChart(
  doc: jsPDF,
  theme: ExportTheme,
  data: PortfolioExecReportData,
  top: number,
): number {
  const series = chartSeries(data.curve);
  const width = contentWidth(doc);
  const boxH = mm(62);
  const padLeft = mm(24);
  const padBottom = mm(10);
  const plotLeft = PAGE.margin + padLeft;
  const plotW = width - padLeft - mm(2);
  const plotTop = top + mm(4);
  const plotH = boxH - padBottom - mm(8);

  // Frame
  doc.setDrawColor(NEUTRAL.line[0], NEUTRAL.line[1], NEUTRAL.line[2]);
  doc.setLineWidth(0.6);
  doc.rect(PAGE.margin, top, width, boxH);

  if (series.months.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(FONT.body);
    doc.setTextColor(NEUTRAL.muted[0], NEUTRAL.muted[1], NEUTRAL.muted[2]);
    doc.text("No cash movements in the reporting period.", PAGE.margin + mm(6), top + boxH / 2);
    resetInk(doc);
    return top + boxH + mm(6);
  }

  // Gridlines + y labels
  doc.setFontSize(FONT.caption - 0.5);
  series.scale.ticks.forEach((tick) => {
    const y = plotY(tick, series.scale, plotTop, plotH);
    doc.setDrawColor(NEUTRAL.line[0], NEUTRAL.line[1], NEUTRAL.line[2]);
    doc.setLineWidth(tick === 0 ? 0.9 : 0.35);
    doc.line(plotLeft, y, plotLeft + plotW, y);
    doc.setTextColor(NEUTRAL.muted[0], NEUTRAL.muted[1], NEUTRAL.muted[2]);
    doc.text(compact(tick), plotLeft - mm(2), y + 2.5, { align: "right" });
  });

  // Series
  const draw = (values: number[], color: Rgb, dashed: boolean) => {
    doc.setDrawColor(color[0], color[1], color[2]);
    doc.setLineWidth(1.4);
    if (dashed) doc.setLineDashPattern([3, 2], 0);
    for (let i = 1; i < values.length; i++) {
      doc.line(
        plotX(i - 1, values.length, plotLeft, plotW),
        plotY(values[i - 1], series.scale, plotTop, plotH),
        plotX(i, values.length, plotLeft, plotW),
        plotY(values[i], series.scale, plotTop, plotH),
      );
    }
    doc.setLineDashPattern([], 0);
    doc.setFillColor(color[0], color[1], color[2]);
    values.forEach((v, i) => {
      doc.circle(
        plotX(i, values.length, plotLeft, plotW),
        plotY(v, series.scale, plotTop, plotH),
        1.5,
        "F",
      );
    });
  };
  draw(series.forecast, theme.accent, true);
  draw(series.actual, theme.primary, false);

  // X labels (thin out so they never collide)
  const every = Math.ceil(series.months.length / 8);
  doc.setFontSize(FONT.caption - 0.5);
  doc.setTextColor(NEUTRAL.muted[0], NEUTRAL.muted[1], NEUTRAL.muted[2]);
  series.months.forEach((m, i) => {
    if (i % every !== 0 && i !== series.months.length - 1) return;
    doc.text(monthLabel(m), plotX(i, series.months.length, plotLeft, plotW), top + boxH - mm(3), {
      align: "center",
    });
  });

  // Legend
  const legendY = top + boxH + mm(5);
  const legend: Array<[string, Rgb, boolean]> = [
    ["Actual net cash", theme.primary, false],
    ["Forecast net cash", theme.accent, true],
  ];
  let lx = PAGE.margin;
  legend.forEach(([label, color, dashed]) => {
    doc.setDrawColor(color[0], color[1], color[2]);
    doc.setLineWidth(1.4);
    if (dashed) doc.setLineDashPattern([3, 2], 0);
    doc.line(lx, legendY - 2, lx + mm(8), legendY - 2);
    doc.setLineDashPattern([], 0);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(FONT.caption);
    doc.setTextColor(NEUTRAL.body[0], NEUTRAL.body[1], NEUTRAL.body[2]);
    doc.text(label, lx + mm(10), legendY);
    lx += mm(50);
  });
  resetInk(doc);
  return legendY + mm(5);
}

function compact(v: number): string {
  const abs = Math.abs(v);
  const sign = v < 0 ? "-" : "";
  if (abs >= 1_000_000) return `${sign}${(abs / 1_000_000).toFixed(1)}M`;
  if (abs >= 1_000) return `${sign}${Math.round(abs / 1_000)}K`;
  return `${sign}${Math.round(abs)}`;
}

function drawCashPage(doc: jsPDF, theme: ExportTheme, data: PortfolioExecReportData): void {
  const cur = data.baseCurrency;
  const subtitle = periodLabel(data.period);
  doc.addPage();
  let y = drawHeaderBand(doc, theme, DOC_TITLE, subtitle);
  y = docH1(doc, "Consolidated cash curve", y);
  y = docCaption(
    doc,
    `All amounts in ${cur}, converted at the FX rate captured when each entry was recorded.`,
    y,
  );
  y = drawCashChart(doc, theme, data, y + mm(1));

  const totals = curveTotals(data.curve);
  const body = data.curve.map((m) => [
    monthLabel(m.month),
    money(m.forecast_inflow, cur),
    money(m.forecast_outflow, cur),
    money(m.forecast_net, cur),
    money(m.actual_inflow, cur),
    money(m.actual_outflow, cur),
    money(m.actual_net, cur),
  ]);
  body.push([
    "Total",
    money(totals.forecast_inflow, cur),
    money(totals.forecast_outflow, cur),
    money(totals.forecast_net, cur),
    money(totals.actual_inflow, cur),
    money(totals.actual_outflow, cur),
    money(totals.actual_net, cur),
  ]);

  docTable(doc, theme, {
    startY: y + mm(4),
    pageHeader: { title: DOC_TITLE, subtitle },
    head: [
      [
        "Month",
        "Forecast in",
        "Forecast out",
        "Forecast net",
        "Actual in",
        "Actual out",
        "Actual net",
      ],
    ],
    body: body.length ? body : [["No cash movements", "—", "—", "—", "—", "—", "—"]],
    totalRows: data.curve.length ? [body.length - 1] : [],
    styles: { fontSize: 7.6 },
    columnStyles: {
      1: numericCol,
      2: numericCol,
      3: numericCol,
      4: numericCol,
      5: numericCol,
      6: numericCol,
    },
  });
}

// ---------------------------------------------------------------------------
// Page 3 — gate rail + project summary

function drawGateRail(
  doc: jsPDF,
  theme: ExportTheme,
  data: PortfolioExecReportData,
  top: number,
): number {
  const width = contentWidth(doc);
  const labelW = mm(48);
  const railLeft = PAGE.margin + labelW;
  const railW = width - labelW - mm(4);
  const rowH = mm(11);
  let y = top;

  // Phase headings
  doc.setFont("helvetica", "bold");
  doc.setFontSize(FONT.caption);
  doc.setTextColor(NEUTRAL.muted[0], NEUTRAL.muted[1], NEUTRAL.muted[2]);
  PHASE_RAIL.forEach((phase, i) => {
    doc.text(titleCase(phase === "cod" ? "COD" : phase), plotX(i, PHASE_RAIL.length, railLeft, railW), y, {
      align: "center",
    });
  });
  y += mm(5);

  const rows = data.gates.length ? data.gates : [];
  if (rows.length === 0) {
    resetInk(doc);
    return docCaption(doc, "No projects with recorded phase gates.", y + mm(2));
  }

  rows.forEach((row) => {
    const cy = y + rowH / 2;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(FONT.caption);
    doc.setTextColor(NEUTRAL.ink[0], NEUTRAL.ink[1], NEUTRAL.ink[2]);
    doc.text(sanitize(row.project_code), PAGE.margin, cy - 2);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(NEUTRAL.muted[0], NEUTRAL.muted[1], NEUTRAL.muted[2]);
    doc.text(
      doc.splitTextToSize(sanitize(row.project_name), labelW - mm(4))[0] ?? "",
      PAGE.margin,
      cy + 6,
    );

    doc.setDrawColor(NEUTRAL.line[0], NEUTRAL.line[1], NEUTRAL.line[2]);
    doc.setLineWidth(1.2);
    doc.line(railLeft, cy, railLeft + railW, cy);

    const active = railIndex(row.phase);
    doc.setLineWidth(1.6);
    doc.setDrawColor(theme.primary[0], theme.primary[1], theme.primary[2]);
    if (active > 0) {
      doc.line(railLeft, cy, plotX(active, PHASE_RAIL.length, railLeft, railW), cy);
    }
    PHASE_RAIL.forEach((_, i) => {
      const x = plotX(i, PHASE_RAIL.length, railLeft, railW);
      const reached = i <= active;
      const color = reached ? theme.primary : NEUTRAL.line;
      doc.setFillColor(color[0], color[1], color[2]);
      doc.circle(x, cy, i === active ? 3.4 : 2.4, "F");
    });
    y += rowH;
  });
  resetInk(doc);
  return y + mm(2);
}

function drawProjectsPage(doc: jsPDF, theme: ExportTheme, data: PortfolioExecReportData): void {
  const cur = data.baseCurrency;
  const subtitle = periodLabel(data.period);
  doc.addPage();
  let y = drawHeaderBand(doc, theme, DOC_TITLE, subtitle);
  y = docH1(doc, "Phase-gate position", y);
  y = drawGateRail(doc, theme, data, y + mm(2));

  y = docH2(doc, theme, "Project summary", y + mm(6));
  const body = data.cards.map((c) => [
    `${sanitize(c.project_code)}\n${sanitize(c.project_name)}`,
    titleCase(c.phase),
    sanitize(c.current_gate_name ?? "—"),
    c.next_gate_name ? `${sanitize(c.next_gate_name)}\n${sanitize(c.next_gate_due ?? "—")}` : "—",
    money(c.contract_value, c.currency_code || cur),
    fmtIndex(c.spi),
    fmtIndex(c.cpi),
    fmtNum(c.punch_a_open),
  ]);

  docTable(doc, theme, {
    startY: y,
    pageHeader: { title: DOC_TITLE, subtitle },
    head: [
      ["Project", "Phase", "Current gate", "Next gate / due", "Contract value", "SPI", "CPI", "Punch A"],
    ],
    body: body.length ? body : [["No projects in scope", "—", "—", "—", "—", "—", "—", "—"]],
    styles: { fontSize: 7.8 },
    columnStyles: { 4: numericCol, 5: numericCol, 6: numericCol, 7: numericCol },
  });
}

// ---------------------------------------------------------------------------
// Page 4 — HSE / quality exposure

function drawExposurePage(doc: jsPDF, theme: ExportTheme, data: PortfolioExecReportData): void {
  const subtitle = periodLabel(data.period);
  const ex = data.exposure;
  doc.addPage();
  let y = drawHeaderBand(doc, theme, DOC_TITLE, subtitle);
  y = docH1(doc, "HSE and quality exposure", y);

  const trend = trirTrend(ex.trir_current, ex.trir_prior);
  const arrow = trend.direction === "down" ? "v" : trend.direction === "up" ? "^" : "-";
  y = drawBigNumbers(
    doc,
    theme,
    [
      { label: "Open incidents", value: fmtNum(ex.incidents_open) },
      {
        label: "TRIR (12 months)",
        value: ex.trir_current === null ? "—" : Number(ex.trir_current).toFixed(2),
        hint:
          trend.direction === "unknown"
            ? "No comparable prior period"
            : `${arrow} vs prior ${ex.trir_prior === null ? "—" : Number(ex.trir_prior).toFixed(2)}`,
      },
      { label: "Open punch items", value: fmtNum(totalCounts(ex.punch_open)) },
      { label: "Open hold points", value: fmtNum(ex.hold_points_open) },
    ],
    y,
    { perRow: 4 },
  );

  y = docH2(doc, theme, "Open incidents by severity", y + mm(6));
  y = docTable(doc, theme, {
    startY: y,
    pageHeader: { title: DOC_TITLE, subtitle },
    head: [["Severity", "Open"]],
    body: orderedCounts(ex.incidents_by_severity, SEVERITY_ORDER).map((r) => [
      titleCase(r.key),
      fmtNum(r.count),
    ]),
    columnStyles: { 1: numericCol },
  });

  y = docH2(doc, theme, "Open quality exposure", y + mm(6));
  const ncr = Object.entries(ex.ncr_open_by_status ?? {}).sort((a, b) => a[0].localeCompare(b[0]));
  y = docTable(doc, theme, {
    startY: y,
    pageHeader: { title: DOC_TITLE, subtitle },
    head: [["Category", "Open"]],
    body: [
      ...orderedCounts(ex.punch_open, PUNCH_ORDER).map((r) => [
        `Punch ${r.key}${r.key === "A" ? " (gate-blocking)" : ""}`,
        fmtNum(r.count),
      ]),
      ...(ncr.length
        ? ncr.map(([status, n]) => [`NCR — ${titleCase(status)}`, fmtNum(n)])
        : [["NCR — none open", "0"]]),
      ["ITP hold points open", fmtNum(ex.hold_points_open)],
    ],
    columnStyles: { 1: numericCol },
  });

  y = docH2(doc, theme, "Project exposure heat table", y + mm(6));
  const heat = sortByExposure(ex.by_project);
  const maxima = EXPOSURE_DIMENSIONS.map((dim) =>
    Math.max(0, ...heat.map((r) => Number(r[dim] ?? 0))),
  );
  docTable(doc, theme, {
    startY: y,
    pageHeader: { title: DOC_TITLE, subtitle },
    head: [["Project", "Incidents", "Punch A", "Punch B", "NCRs", "Hold points", "Days since"]],
    body: heat.length
      ? heat.map((r) => [
          `${sanitize(r.project_code)}\n${sanitize(r.project_name)}`,
          fmtNum(r.incidents_open),
          fmtNum(r.punch_a_open),
          fmtNum(r.punch_b_open),
          fmtNum(r.ncr_open),
          fmtNum(r.hold_points_open),
          r.days_since_last_incident === null ? "—" : fmtNum(r.days_since_last_incident),
        ])
      : [["No projects in scope", "—", "—", "—", "—", "—", "—"]],
    styles: { fontSize: 7.8 },
    columnStyles: {
      1: numericCol,
      2: numericCol,
      3: numericCol,
      4: numericCol,
      5: numericCol,
      6: numericCol,
    },
    didParseCell: (cell) => {
      if (cell.section !== "body" || cell.column.index === 0 || cell.column.index > 5) return;
      const row = heat[cell.row.index];
      if (!row) return;
      const dim = EXPOSURE_DIMENSIONS[cell.column.index - 1];
      const value = Number(row[dim] ?? 0);
      const max = maxima[cell.column.index - 1] || 0;
      if (value <= 0) return;
      const share = max > 0 ? value / max : 1;
      cell.cell.styles.fillColor = tint([190, 45, 45], 1 - Math.min(1, 0.25 + share * 0.55)) as Rgb;
      cell.cell.styles.fontStyle = "bold";
      cell.cell.styles.halign = "right";
    },
  });
}

// ---------------------------------------------------------------------------
// Footers (page numbers + confidentiality + live-data stamp + language note)

function drawExecFooters(doc: jsPDF, theme: ExportTheme, data: PortfolioExecReportData): void {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(FONT.footer - 0.5);
    doc.setTextColor(NEUTRAL.muted[0], NEUTRAL.muted[1], NEUTRAL.muted[2]);
    doc.setDrawColor(NEUTRAL.line[0], NEUTRAL.line[1], NEUTRAL.line[2]);
    doc.setLineWidth(0.5);
    doc.line(PAGE.margin, pageH - mm(16), pageW - PAGE.margin, pageH - mm(16));
    doc.text(
      `${CONFIDENTIALITY_NOTE} ${LANGUAGE_NOTE}`,
      PAGE.margin,
      pageH - mm(12),
    );
    doc.text(
      `${theme.footerLeft || sanitize(data.company.name)} · ${LIVE_DATA_STAMP} ${utcDateTime(
        data.generatedAt,
      )}`,
      PAGE.margin,
      pageH - mm(8),
    );
    doc.text(`Page ${i} of ${total}`, pageW - PAGE.margin, pageH - mm(8), { align: "right" });
  }
  resetInk(doc);
}

// ---------------------------------------------------------------------------
// Entry point

export interface ExecReportPdf {
  bytes: Uint8Array;
  filename: string;
}

/**
 * Pure generator: PortfolioExecReportData → PDF bytes. Safe to call from a
 * browser click handler or, later, from the scheduled-reports runner.
 */
export async function buildPortfolioExecReportPdf(
  data: PortfolioExecReportData,
): Promise<ExecReportPdf> {
  const theme = await createExportTheme(
    {
      primaryColor: data.branding.primaryColor,
      accentColor: data.branding.accentColor,
      footerText: data.branding.footerText,
      logoSignedUrl: data.branding.logoSignedUrl,
    },
    { name: data.company.name, legal_name: data.company.legalName },
  );

  const doc = createDoc();
  drawCover(doc, theme, data);
  doc.addPage();
  drawKpiPage(doc, theme, data);
  drawCashPage(doc, theme, data);
  drawProjectsPage(doc, theme, data);
  drawExposurePage(doc, theme, data);
  drawExecFooters(doc, theme, data);

  const buf = doc.output("arraybuffer");
  return {
    bytes: new Uint8Array(buf),
    filename: execReportFilename(data.company.name, data.period),
  };
}
