// P-092 — Weekly client report PDF builder (client-side jsPDF), on the shared export theme.
import autoTable from "jspdf-autotable";
import type { jsPDF } from "jspdf";

import type { WeeklyReportDTO, WeeklyReportPhotoDTO } from "@/lib/field-reports.functions";
import {
  createDoc,
  createExportThemeSync,
  contentWidth,
  drawHeaderBand,
  drawFooters,
  drawBigNumbers,
  docH2,
  docCaption,
  docBody,
  ensureSpace,
  docTable,
  numericCol,
  tableEndY,
  sanitize,
  fmtNum,
  fmtPct,
  fmtDate,
  fetchImageDataUrl,
  imageFormat,
  slugify,
  resetInk,
  FONT,
  PAGE,
  mm,
  NEUTRAL,
} from "@/lib/exports/theme";

export async function buildWeeklyReportPdfBytes(input: WeeklyReportDTO): Promise<Uint8Array> {
  const theme = createExportThemeSync(
    {
      primaryColor: input.branding.primaryColor,
      accentColor: input.branding.accentColor,
      footerText: input.branding.footerText || `Generated by GridMind EPC · ${input.company.name}`,
      logoDataUrl: await fetchImageDataUrl(input.branding.logoSignedUrl),
    },
    input.company,
  );

  const doc = createDoc();
  const docTitle = "Weekly Construction Report";
  const subtitle = sanitize(`${input.project.name} · ${input.isoWeekLabel}`);

  let y = drawHeaderBand(doc, theme, docTitle, subtitle);

  // ---- Project meta caption ----------------------------------------------
  const metaBits = [
    input.project.code ? `Code ${input.project.code}` : null,
    input.project.archetype ? sanitize(input.project.archetype) : null,
    input.project.capacityMw != null ? `${fmtNum(input.project.capacityMw, 1)} MW` : null,
    `${fmtDate(input.weekStart)} – ${fmtDate(input.weekEnd)}`,
  ].filter(Boolean) as string[];
  y = docCaption(doc, metaBits.join(" · "), y);
  y += mm(2);

  // ---- KPI strip: 4 uniform big-number blocks ---------------------------
  y = drawBigNumbers(
    doc,
    theme,
    [
      { label: "SPI", value: fmtNum(input.kpis.spi, 2) },
      { label: "CPI", value: fmtNum(input.kpis.cpi, 2) },
      { label: "TRIR (12m)", value: fmtNum(input.kpis.trir12m, 2) },
      { label: "Rework %", value: fmtPct(input.kpis.reworkPct) },
    ],
    y,
    { perRow: 4 },
  );
  y += mm(4);

  // ---- Daily log table ----------------------------------------------------
  y = ensureSpace(doc, theme, y, mm(40), docTitle);
  y = docH2(doc, theme, "Daily log", y);
  y =
    docTable(doc, theme, {
      startY: y,
      pageHeader: { title: docTitle, subtitle },
      head: [["Date", "Shift", "Manpower", "Hours", "Weather", "Work summary"]],
      body:
        input.daily.length > 0
          ? input.daily.map((r) => [
              r.reportDate,
              sanitize(r.shift),
              String(r.totalManpower),
              fmtNum(r.totalHours, 1),
              sanitize(r.weatherSummary ?? ""),
              sanitize(r.workSummary ?? ""),
            ])
          : [["—", "—", "—", "—", "—", "No DPRs submitted this week"]],
      columnStyles: {
        2: numericCol,
        3: numericCol,
      },
    }) + mm(6);

  // ---- Discipline / area --------------------------------------------------
  y = ensureSpace(doc, theme, y, mm(50), docTitle);
  y = docH2(doc, theme, "Installed quantities by discipline / area", y);
  y =
    docTable(doc, theme, {
      startY: y,
      pageHeader: { title: docTitle, subtitle },
      head: [["Discipline", "Area", "UoM", "Installed this week", "Daily rate", "Planned (WBS)"]],
      body:
        input.disciplines.length > 0
          ? input.disciplines.map((d) => [
              sanitize(d.discipline),
              sanitize(d.area),
              sanitize(d.uom ?? "—"),
              fmtNum(d.installedThisWeek, 2),
              fmtNum(d.dailyRate, 2),
              fmtNum(d.planned, 2),
            ])
          : [["—", "—", "—", "—", "—", "—"]],
      columnStyles: {
        3: numericCol,
        4: numericCol,
        5: numericCol,
      },
    }) + mm(6);

  // ---- Weather delays -------------------------------------------------
  if (input.weather.length > 0) {
    y = ensureSpace(doc, theme, y, mm(40), docTitle);
    y = docH2(doc, theme, "Weather delays (lost hours)", y);
    y =
      docTable(doc, theme, {
        startY: y,
        pageHeader: { title: docTitle, subtitle },
        head: [["Type", "Events", "Lost hours"]],
        body: input.weather.map((w) => [
          sanitize(w.delayType),
          String(w.count),
          fmtNum(w.hours, 1),
        ]),
        columnStyles: { 1: numericCol, 2: numericCol },
      }) + mm(6);
  }

  // ---- HSE + QA two-column summaries --------------------------------------
  y = ensureSpace(doc, theme, y, mm(60), docTitle);
  const width = contentWidth(doc);
  const gutter = mm(6);
  const halfW = (width - gutter) / 2;
  const hseY = y;

  y = docH2(doc, theme, "HSE summary", y);
  const hseTitleEnd = y;
  // Right-column heading: docH2 always draws at the left margin, so the QA/QC
  // title is drawn manually in the second column to avoid overlapping it.
  doc.setFont("helvetica", "bold");
  doc.setFontSize(FONT.h2);
  doc.setTextColor(theme.primary[0], theme.primary[1], theme.primary[2]);
  doc.text(sanitize("QA/QC summary"), PAGE.margin + halfW + gutter, hseY);
  resetInk(doc);

  const hseBody: string[][] = [
    ["Recordables this week", String(input.hse.recordablesThisWeek)],
    ["TRIR (trailing 12 months)", fmtNum(input.hse.trir12m, 2)],
    ["Recordables (12m)", String(input.hse.recordables12m)],
    ["Man-hours (12m)", fmtNum(input.hse.hours12m, 0)],
    ...input.hse.incidentsByType.map((r) => [sanitize(r.type), String(r.count)]),
  ];
  const qaBody: string[][] = [
    ["Inspections run", String(input.qa.inspectionsRun)],
    ["Pass rate", fmtPct(input.qa.passRate)],
    ["Rework %", fmtPct(input.qa.reworkPct)],
    ["Open punch — A (critical)", String(input.qa.openPunchByCategory.A)],
    ["Open punch — B", String(input.qa.openPunchByCategory.B)],
    ["Open punch — C", String(input.qa.openPunchByCategory.C)],
  ];

  autoTable(doc, {
    startY: hseTitleEnd,
    body: hseBody,
    tableWidth: halfW,
    margin: { left: PAGE.margin },
    theme: "plain",
    styles: { font: "helvetica", fontSize: 9, cellPadding: 4, textColor: NEUTRAL.body as never },
    columnStyles: { 1: { ...numericCol, cellWidth: mm(18) } },
    alternateRowStyles: { fillColor: NEUTRAL.stripe as never },
  });
  const hseEnd = tableEndY(doc, hseTitleEnd);

  autoTable(doc, {
    startY: hseTitleEnd,
    body: qaBody,
    tableWidth: halfW,
    margin: { left: PAGE.margin + halfW + gutter },
    theme: "plain",
    styles: { font: "helvetica", fontSize: 9, cellPadding: 4, textColor: NEUTRAL.body as never },
    columnStyles: { 1: { ...numericCol, cellWidth: mm(18) } },
    alternateRowStyles: { fillColor: NEUTRAL.stripe as never },
  });
  const qaEnd = tableEndY(doc, hseTitleEnd);
  y = Math.max(hseEnd, qaEnd) + mm(6);

  // ---- Lookahead -----------------------------------------------------------
  if (input.lookahead.topWeatherImpacts.length > 0 || input.lookahead.plannedAreas.length > 0) {
    y = ensureSpace(doc, theme, y, mm(50), docTitle);
    y = docH2(doc, theme, "Next-week lookahead", y);

    const wImp =
      input.lookahead.topWeatherImpacts
        .map((w) => `${sanitize(w.delayType)}: ${fmtNum(w.hours, 1)}h`)
        .join(" · ") || "None";
    y = docBody(doc, `Top weather impacts (this week): ${wImp}`, y);

    const planned =
      input.lookahead.plannedAreas
        .map(
          (t) =>
            `${sanitize(t.name)}${t.discipline ? ` (${sanitize(t.discipline)})` : ""} — ${fmtDate(t.start)}`,
        )
        .join("; ") || "None scheduled";
    y = docBody(doc, `Planned areas next week: ${planned}`, y) + mm(2);
  }

  // ---- Photo strip ---------------------------------------------------------
  if (input.photos.length > 0) {
    y = ensureSpace(doc, theme, y, mm(70), docTitle);
    y = docH2(doc, theme, "Site photos", y);
    await drawPhotoStrip(doc, input.photos, y);
  }

  drawFooters(doc, theme);

  const ab = doc.output("arraybuffer");
  return new Uint8Array(ab);
}

async function drawPhotoStrip(doc: jsPDF, photos: WeeklyReportPhotoDTO[], y: number) {
  const items = photos.slice(0, 6);
  const totalW = contentWidth(doc);
  const gap = mm(3);
  const cols = 3;
  const cellW = (totalW - gap * (cols - 1)) / cols;
  const cellH = mm(38);
  for (let i = 0; i < items.length; i++) {
    const row = Math.floor(i / cols);
    const col = i % cols;
    const cx = PAGE.margin + col * (cellW + gap);
    const cy = y + row * (cellH + gap + mm(5));
    doc.setDrawColor(NEUTRAL.line[0], NEUTRAL.line[1], NEUTRAL.line[2]);
    doc.setFillColor(NEUTRAL.stripe[0], NEUTRAL.stripe[1], NEUTRAL.stripe[2]);
    doc.roundedRect(cx, cy, cellW, cellH, 3, 3, "FD");

    const dataUrl = await fetchImageDataUrl(items[i].signedUrl);
    if (dataUrl) {
      try {
        doc.addImage(dataUrl, imageFormat(dataUrl), cx + 2, cy + 2, cellW - 4, cellH - 4);
      } catch {
        /* ignore malformed image */
      }
    }
    if (items[i].caption) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(NEUTRAL.muted[0], NEUTRAL.muted[1], NEUTRAL.muted[2]);
      doc.text(sanitize(items[i].caption).slice(0, 60), cx, cy + cellH + mm(4), {
        maxWidth: cellW,
      });
    }
  }
}

export function weeklyReportFilename(projectName: string, weekLabel: string): string {
  return `weekly-${slugify(projectName, 40)}-${weekLabel}.pdf`;
}
