/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedProposalsIndexRouteImport } from './routes/_authenticated/proposals.index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as ApiWebhooksEsignRouteImport } from './routes/api/webhooks/esign'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings.users'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsPermissionsSimulatorRouteImport } from './routes/_authenticated/settings.permissions-simulator'
import { Route as AuthenticatedSettingsModulesRouteImport } from './routes/_authenticated/settings.modules'
import { Route as AuthenticatedSettingsDepartmentsRouteImport } from './routes/_authenticated/settings.departments'
import { Route as AuthenticatedSettingsCompanyRouteImport } from './routes/_authenticated/settings.company'
import { Route as AuthenticatedProposalsProposalIdRouteImport } from './routes/_authenticated/proposals.$proposalId'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects.new'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedCrmPipelineRouteImport } from './routes/_authenticated/crm.pipeline'
import { Route as AuthenticatedAdminTenantsRouteRouteImport } from './routes/_authenticated/admin.tenants.route'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects.$projectId.index'
import { Route as AuthenticatedAdminTenantsIndexRouteImport } from './routes/_authenticated/admin.tenants.index'
import { Route as AuthenticatedProjectsProjectIdProcurementRouteImport } from './routes/_authenticated/projects.$projectId.procurement'
import { Route as AuthenticatedProjectsProjectIdOverviewRouteImport } from './routes/_authenticated/projects.$projectId.overview'
import { Route as AuthenticatedProjectsProjectIdHseRouteImport } from './routes/_authenticated/projects.$projectId.hse'
import { Route as AuthenticatedProjectsProjectIdGatesRouteImport } from './routes/_authenticated/projects.$projectId.gates'
import { Route as AuthenticatedProjectsProjectIdFinanceRouteImport } from './routes/_authenticated/projects.$projectId.finance'
import { Route as AuthenticatedProjectsProjectIdEngineeringRouteImport } from './routes/_authenticated/projects.$projectId.engineering'
import { Route as AuthenticatedProjectsProjectIdConstructionRouteImport } from './routes/_authenticated/projects.$projectId.construction'
import { Route as AuthenticatedProjectsProjectIdConfigRouteImport } from './routes/_authenticated/projects.$projectId.config'
import { Route as AuthenticatedCrmOpportunitiesOpportunityIdRouteImport } from './routes/_authenticated/crm.opportunities.$opportunityId'
import { Route as AuthenticatedAdminTenantsCompanyIdRouteImport } from './routes/_authenticated/admin.tenants.$companyId'
import { Route as AuthenticatedProjectsProjectIdEngineeringIndexRouteImport } from './routes/_authenticated/projects.$projectId.engineering.index'
import { Route as AuthenticatedProjectsProjectIdEngineeringYieldRouteImport } from './routes/_authenticated/projects.$projectId.engineering.yield'
import { Route as AuthenticatedProjectsProjectIdEngineeringUploadsRouteImport } from './routes/_authenticated/projects.$projectId.engineering.uploads'
import { Route as AuthenticatedProjectsProjectIdEngineeringSldRouteImport } from './routes/_authenticated/projects.$projectId.engineering.sld'
import { Route as AuthenticatedProjectsProjectIdEngineeringReviewsRouteImport } from './routes/_authenticated/projects.$projectId.engineering.reviews'
import { Route as AuthenticatedProjectsProjectIdEngineeringDrawingsRouteImport } from './routes/_authenticated/projects.$projectId.engineering.drawings'
import { Route as AuthenticatedProjectsProjectIdEngineeringBomRouteImport } from './routes/_authenticated/projects.$projectId.engineering.bom'
import { Route as AuthenticatedProjectsProjectIdEngineeringDrawingsIndexRouteImport } from './routes/_authenticated/projects.$projectId.engineering.drawings.index'
import { Route as AuthenticatedProjectsProjectIdEngineeringDrawingsDrawingIdRouteImport } from './routes/_authenticated/projects.$projectId.engineering.drawings.$drawingId'

const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const AuthenticatedProposalsIndexRoute =
  AuthenticatedProposalsIndexRouteImport.update({
    id: '/proposals/',
    path: '/proposals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiWebhooksEsignRoute = ApiWebhooksEsignRouteImport.update({
  id: '/api/webhooks/esign',
  path: '/api/webhooks/esign',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPermissionsSimulatorRoute =
  AuthenticatedSettingsPermissionsSimulatorRouteImport.update({
    id: '/settings/permissions-simulator',
    path: '/settings/permissions-simulator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsModulesRoute =
  AuthenticatedSettingsModulesRouteImport.update({
    id: '/settings/modules',
    path: '/settings/modules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsDepartmentsRoute =
  AuthenticatedSettingsDepartmentsRouteImport.update({
    id: '/settings/departments',
    path: '/settings/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCompanyRoute =
  AuthenticatedSettingsCompanyRouteImport.update({
    id: '/settings/company',
    path: '/settings/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsProposalIdRoute =
  AuthenticatedProposalsProposalIdRouteImport.update({
    id: '/proposals/$proposalId',
    path: '/proposals/$proposalId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmPipelineRoute =
  AuthenticatedCrmPipelineRouteImport.update({
    id: '/crm/pipeline',
    path: '/crm/pipeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTenantsRouteRoute =
  AuthenticatedAdminTenantsRouteRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedAdminTenantsIndexRoute =
  AuthenticatedAdminTenantsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminTenantsRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdProcurementRoute =
  AuthenticatedProjectsProjectIdProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdOverviewRoute =
  AuthenticatedProjectsProjectIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdHseRoute =
  AuthenticatedProjectsProjectIdHseRouteImport.update({
    id: '/hse',
    path: '/hse',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdGatesRoute =
  AuthenticatedProjectsProjectIdGatesRouteImport.update({
    id: '/gates',
    path: '/gates',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdFinanceRoute =
  AuthenticatedProjectsProjectIdFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdEngineeringRoute =
  AuthenticatedProjectsProjectIdEngineeringRouteImport.update({
    id: '/engineering',
    path: '/engineering',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdConstructionRoute =
  AuthenticatedProjectsProjectIdConstructionRouteImport.update({
    id: '/construction',
    path: '/construction',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdConfigRoute =
  AuthenticatedProjectsProjectIdConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedCrmOpportunitiesOpportunityIdRoute =
  AuthenticatedCrmOpportunitiesOpportunityIdRouteImport.update({
    id: '/crm/opportunities/$opportunityId',
    path: '/crm/opportunities/$opportunityId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTenantsCompanyIdRoute =
  AuthenticatedAdminTenantsCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AuthenticatedAdminTenantsRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdEngineeringIndexRoute =
  AuthenticatedProjectsProjectIdEngineeringIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdEngineeringRoute,
  } as any)
const AuthenticatedProjectsProjectIdEngineeringYieldRoute =
  AuthenticatedProjectsProjectIdEngineeringYieldRouteImport.update({
    id: '/yield',
    path: '/yield',
    getParentRoute: () => AuthenticatedProjectsProjectIdEngineeringRoute,
  } as any)
const AuthenticatedProjectsProjectIdEngineeringUploadsRoute =
  AuthenticatedProjectsProjectIdEngineeringUploadsRouteImport.update({
    id: '/uploads',
    path: '/uploads',
    getParentRoute: () => AuthenticatedProjectsProjectIdEngineeringRoute,
  } as any)
const AuthenticatedProjectsProjectIdEngineeringSldRoute =
  AuthenticatedProjectsProjectIdEngineeringSldRouteImport.update({
    id: '/sld',
    path: '/sld',
    getParentRoute: () => AuthenticatedProjectsProjectIdEngineeringRoute,
  } as any)
const AuthenticatedProjectsProjectIdEngineeringReviewsRoute =
  AuthenticatedProjectsProjectIdEngineeringReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedProjectsProjectIdEngineeringRoute,
  } as any)
const AuthenticatedProjectsProjectIdEngineeringDrawingsRoute =
  AuthenticatedProjectsProjectIdEngineeringDrawingsRouteImport.update({
    id: '/drawings',
    path: '/drawings',
    getParentRoute: () => AuthenticatedProjectsProjectIdEngineeringRoute,
  } as any)
const AuthenticatedProjectsProjectIdEngineeringBomRoute =
  AuthenticatedProjectsProjectIdEngineeringBomRouteImport.update({
    id: '/bom',
    path: '/bom',
    getParentRoute: () => AuthenticatedProjectsProjectIdEngineeringRoute,
  } as any)
const AuthenticatedProjectsProjectIdEngineeringDrawingsIndexRoute =
  AuthenticatedProjectsProjectIdEngineeringDrawingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedProjectsProjectIdEngineeringDrawingsRoute,
  } as any)
const AuthenticatedProjectsProjectIdEngineeringDrawingsDrawingIdRoute =
  AuthenticatedProjectsProjectIdEngineeringDrawingsDrawingIdRouteImport.update({
    id: '/$drawingId',
    path: '/$drawingId',
    getParentRoute: () =>
      AuthenticatedProjectsProjectIdEngineeringDrawingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRouteRouteWithChildren
  '/crm/pipeline': typeof AuthenticatedCrmPipelineRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/proposals/$proposalId': typeof AuthenticatedProposalsProposalIdRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/departments': typeof AuthenticatedSettingsDepartmentsRoute
  '/settings/modules': typeof AuthenticatedSettingsModulesRoute
  '/settings/permissions-simulator': typeof AuthenticatedSettingsPermissionsSimulatorRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/api/webhooks/esign': typeof ApiWebhooksEsignRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/proposals/': typeof AuthenticatedProposalsIndexRoute
  '/admin/tenants/$companyId': typeof AuthenticatedAdminTenantsCompanyIdRoute
  '/crm/opportunities/$opportunityId': typeof AuthenticatedCrmOpportunitiesOpportunityIdRoute
  '/projects/$projectId/config': typeof AuthenticatedProjectsProjectIdConfigRoute
  '/projects/$projectId/construction': typeof AuthenticatedProjectsProjectIdConstructionRoute
  '/projects/$projectId/engineering': typeof AuthenticatedProjectsProjectIdEngineeringRouteWithChildren
  '/projects/$projectId/finance': typeof AuthenticatedProjectsProjectIdFinanceRoute
  '/projects/$projectId/gates': typeof AuthenticatedProjectsProjectIdGatesRoute
  '/projects/$projectId/hse': typeof AuthenticatedProjectsProjectIdHseRoute
  '/projects/$projectId/overview': typeof AuthenticatedProjectsProjectIdOverviewRoute
  '/projects/$projectId/procurement': typeof AuthenticatedProjectsProjectIdProcurementRoute
  '/admin/tenants/': typeof AuthenticatedAdminTenantsIndexRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/engineering/bom': typeof AuthenticatedProjectsProjectIdEngineeringBomRoute
  '/projects/$projectId/engineering/drawings': typeof AuthenticatedProjectsProjectIdEngineeringDrawingsRouteWithChildren
  '/projects/$projectId/engineering/reviews': typeof AuthenticatedProjectsProjectIdEngineeringReviewsRoute
  '/projects/$projectId/engineering/sld': typeof AuthenticatedProjectsProjectIdEngineeringSldRoute
  '/projects/$projectId/engineering/uploads': typeof AuthenticatedProjectsProjectIdEngineeringUploadsRoute
  '/projects/$projectId/engineering/yield': typeof AuthenticatedProjectsProjectIdEngineeringYieldRoute
  '/projects/$projectId/engineering/': typeof AuthenticatedProjectsProjectIdEngineeringIndexRoute
  '/projects/$projectId/engineering/drawings/$drawingId': typeof AuthenticatedProjectsProjectIdEngineeringDrawingsDrawingIdRoute
  '/projects/$projectId/engineering/drawings/': typeof AuthenticatedProjectsProjectIdEngineeringDrawingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/crm/pipeline': typeof AuthenticatedCrmPipelineRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/proposals/$proposalId': typeof AuthenticatedProposalsProposalIdRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/departments': typeof AuthenticatedSettingsDepartmentsRoute
  '/settings/modules': typeof AuthenticatedSettingsModulesRoute
  '/settings/permissions-simulator': typeof AuthenticatedSettingsPermissionsSimulatorRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/api/webhooks/esign': typeof ApiWebhooksEsignRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/proposals': typeof AuthenticatedProposalsIndexRoute
  '/admin/tenants/$companyId': typeof AuthenticatedAdminTenantsCompanyIdRoute
  '/crm/opportunities/$opportunityId': typeof AuthenticatedCrmOpportunitiesOpportunityIdRoute
  '/projects/$projectId/config': typeof AuthenticatedProjectsProjectIdConfigRoute
  '/projects/$projectId/construction': typeof AuthenticatedProjectsProjectIdConstructionRoute
  '/projects/$projectId/finance': typeof AuthenticatedProjectsProjectIdFinanceRoute
  '/projects/$projectId/gates': typeof AuthenticatedProjectsProjectIdGatesRoute
  '/projects/$projectId/hse': typeof AuthenticatedProjectsProjectIdHseRoute
  '/projects/$projectId/overview': typeof AuthenticatedProjectsProjectIdOverviewRoute
  '/projects/$projectId/procurement': typeof AuthenticatedProjectsProjectIdProcurementRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/engineering/bom': typeof AuthenticatedProjectsProjectIdEngineeringBomRoute
  '/projects/$projectId/engineering/reviews': typeof AuthenticatedProjectsProjectIdEngineeringReviewsRoute
  '/projects/$projectId/engineering/sld': typeof AuthenticatedProjectsProjectIdEngineeringSldRoute
  '/projects/$projectId/engineering/uploads': typeof AuthenticatedProjectsProjectIdEngineeringUploadsRoute
  '/projects/$projectId/engineering/yield': typeof AuthenticatedProjectsProjectIdEngineeringYieldRoute
  '/projects/$projectId/engineering': typeof AuthenticatedProjectsProjectIdEngineeringIndexRoute
  '/projects/$projectId/engineering/drawings/$drawingId': typeof AuthenticatedProjectsProjectIdEngineeringDrawingsDrawingIdRoute
  '/projects/$projectId/engineering/drawings': typeof AuthenticatedProjectsProjectIdEngineeringDrawingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/design-system': typeof DesignSystemRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signup': typeof authSignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRouteRouteWithChildren
  '/_authenticated/crm/pipeline': typeof AuthenticatedCrmPipelineRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/proposals/$proposalId': typeof AuthenticatedProposalsProposalIdRoute
  '/_authenticated/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/_authenticated/settings/departments': typeof AuthenticatedSettingsDepartmentsRoute
  '/_authenticated/settings/modules': typeof AuthenticatedSettingsModulesRoute
  '/_authenticated/settings/permissions-simulator': typeof AuthenticatedSettingsPermissionsSimulatorRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/api/webhooks/esign': typeof ApiWebhooksEsignRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/proposals/': typeof AuthenticatedProposalsIndexRoute
  '/_authenticated/admin/tenants/$companyId': typeof AuthenticatedAdminTenantsCompanyIdRoute
  '/_authenticated/crm/opportunities/$opportunityId': typeof AuthenticatedCrmOpportunitiesOpportunityIdRoute
  '/_authenticated/projects/$projectId/config': typeof AuthenticatedProjectsProjectIdConfigRoute
  '/_authenticated/projects/$projectId/construction': typeof AuthenticatedProjectsProjectIdConstructionRoute
  '/_authenticated/projects/$projectId/engineering': typeof AuthenticatedProjectsProjectIdEngineeringRouteWithChildren
  '/_authenticated/projects/$projectId/finance': typeof AuthenticatedProjectsProjectIdFinanceRoute
  '/_authenticated/projects/$projectId/gates': typeof AuthenticatedProjectsProjectIdGatesRoute
  '/_authenticated/projects/$projectId/hse': typeof AuthenticatedProjectsProjectIdHseRoute
  '/_authenticated/projects/$projectId/overview': typeof AuthenticatedProjectsProjectIdOverviewRoute
  '/_authenticated/projects/$projectId/procurement': typeof AuthenticatedProjectsProjectIdProcurementRoute
  '/_authenticated/admin/tenants/': typeof AuthenticatedAdminTenantsIndexRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/projects/$projectId/engineering/bom': typeof AuthenticatedProjectsProjectIdEngineeringBomRoute
  '/_authenticated/projects/$projectId/engineering/drawings': typeof AuthenticatedProjectsProjectIdEngineeringDrawingsRouteWithChildren
  '/_authenticated/projects/$projectId/engineering/reviews': typeof AuthenticatedProjectsProjectIdEngineeringReviewsRoute
  '/_authenticated/projects/$projectId/engineering/sld': typeof AuthenticatedProjectsProjectIdEngineeringSldRoute
  '/_authenticated/projects/$projectId/engineering/uploads': typeof AuthenticatedProjectsProjectIdEngineeringUploadsRoute
  '/_authenticated/projects/$projectId/engineering/yield': typeof AuthenticatedProjectsProjectIdEngineeringYieldRoute
  '/_authenticated/projects/$projectId/engineering/': typeof AuthenticatedProjectsProjectIdEngineeringIndexRoute
  '/_authenticated/projects/$projectId/engineering/drawings/$drawingId': typeof AuthenticatedProjectsProjectIdEngineeringDrawingsDrawingIdRoute
  '/_authenticated/projects/$projectId/engineering/drawings/': typeof AuthenticatedProjectsProjectIdEngineeringDrawingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/design-system'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/admin/tenants'
    | '/crm/pipeline'
    | '/projects/$projectId'
    | '/projects/new'
    | '/proposals/$proposalId'
    | '/settings/company'
    | '/settings/departments'
    | '/settings/modules'
    | '/settings/permissions-simulator'
    | '/settings/profile'
    | '/settings/users'
    | '/api/webhooks/esign'
    | '/projects/'
    | '/proposals/'
    | '/admin/tenants/$companyId'
    | '/crm/opportunities/$opportunityId'
    | '/projects/$projectId/config'
    | '/projects/$projectId/construction'
    | '/projects/$projectId/engineering'
    | '/projects/$projectId/finance'
    | '/projects/$projectId/gates'
    | '/projects/$projectId/hse'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/procurement'
    | '/admin/tenants/'
    | '/projects/$projectId/'
    | '/projects/$projectId/engineering/bom'
    | '/projects/$projectId/engineering/drawings'
    | '/projects/$projectId/engineering/reviews'
    | '/projects/$projectId/engineering/sld'
    | '/projects/$projectId/engineering/uploads'
    | '/projects/$projectId/engineering/yield'
    | '/projects/$projectId/engineering/'
    | '/projects/$projectId/engineering/drawings/$drawingId'
    | '/projects/$projectId/engineering/drawings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/design-system'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/crm/pipeline'
    | '/projects/new'
    | '/proposals/$proposalId'
    | '/settings/company'
    | '/settings/departments'
    | '/settings/modules'
    | '/settings/permissions-simulator'
    | '/settings/profile'
    | '/settings/users'
    | '/api/webhooks/esign'
    | '/projects'
    | '/proposals'
    | '/admin/tenants/$companyId'
    | '/crm/opportunities/$opportunityId'
    | '/projects/$projectId/config'
    | '/projects/$projectId/construction'
    | '/projects/$projectId/finance'
    | '/projects/$projectId/gates'
    | '/projects/$projectId/hse'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/procurement'
    | '/admin/tenants'
    | '/projects/$projectId'
    | '/projects/$projectId/engineering/bom'
    | '/projects/$projectId/engineering/reviews'
    | '/projects/$projectId/engineering/sld'
    | '/projects/$projectId/engineering/uploads'
    | '/projects/$projectId/engineering/yield'
    | '/projects/$projectId/engineering'
    | '/projects/$projectId/engineering/drawings/$drawingId'
    | '/projects/$projectId/engineering/drawings'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/_authenticated'
    | '/accept-invite'
    | '/design-system'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(auth)/signup'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/tenants'
    | '/_authenticated/crm/pipeline'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/new'
    | '/_authenticated/proposals/$proposalId'
    | '/_authenticated/settings/company'
    | '/_authenticated/settings/departments'
    | '/_authenticated/settings/modules'
    | '/_authenticated/settings/permissions-simulator'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/users'
    | '/api/webhooks/esign'
    | '/_authenticated/projects/'
    | '/_authenticated/proposals/'
    | '/_authenticated/admin/tenants/$companyId'
    | '/_authenticated/crm/opportunities/$opportunityId'
    | '/_authenticated/projects/$projectId/config'
    | '/_authenticated/projects/$projectId/construction'
    | '/_authenticated/projects/$projectId/engineering'
    | '/_authenticated/projects/$projectId/finance'
    | '/_authenticated/projects/$projectId/gates'
    | '/_authenticated/projects/$projectId/hse'
    | '/_authenticated/projects/$projectId/overview'
    | '/_authenticated/projects/$projectId/procurement'
    | '/_authenticated/admin/tenants/'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/projects/$projectId/engineering/bom'
    | '/_authenticated/projects/$projectId/engineering/drawings'
    | '/_authenticated/projects/$projectId/engineering/reviews'
    | '/_authenticated/projects/$projectId/engineering/sld'
    | '/_authenticated/projects/$projectId/engineering/uploads'
    | '/_authenticated/projects/$projectId/engineering/yield'
    | '/_authenticated/projects/$projectId/engineering/'
    | '/_authenticated/projects/$projectId/engineering/drawings/$drawingId'
    | '/_authenticated/projects/$projectId/engineering/drawings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ApiWebhooksEsignRoute: typeof ApiWebhooksEsignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/proposals/': {
      id: '/_authenticated/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof AuthenticatedProposalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/webhooks/esign': {
      id: '/api/webhooks/esign'
      path: '/api/webhooks/esign'
      fullPath: '/api/webhooks/esign'
      preLoaderRoute: typeof ApiWebhooksEsignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/permissions-simulator': {
      id: '/_authenticated/settings/permissions-simulator'
      path: '/settings/permissions-simulator'
      fullPath: '/settings/permissions-simulator'
      preLoaderRoute: typeof AuthenticatedSettingsPermissionsSimulatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/modules': {
      id: '/_authenticated/settings/modules'
      path: '/settings/modules'
      fullPath: '/settings/modules'
      preLoaderRoute: typeof AuthenticatedSettingsModulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/departments': {
      id: '/_authenticated/settings/departments'
      path: '/settings/departments'
      fullPath: '/settings/departments'
      preLoaderRoute: typeof AuthenticatedSettingsDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/company': {
      id: '/_authenticated/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/$proposalId': {
      id: '/_authenticated/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/proposals/$proposalId'
      preLoaderRoute: typeof AuthenticatedProposalsProposalIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/pipeline': {
      id: '/_authenticated/crm/pipeline'
      path: '/crm/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof AuthenticatedCrmPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/admin/tenants/': {
      id: '/_authenticated/admin/tenants/'
      path: '/'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AuthenticatedAdminTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminTenantsRouteRoute
    }
    '/_authenticated/projects/$projectId/procurement': {
      id: '/_authenticated/projects/$projectId/procurement'
      path: '/procurement'
      fullPath: '/projects/$projectId/procurement'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdProcurementRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/overview': {
      id: '/_authenticated/projects/$projectId/overview'
      path: '/overview'
      fullPath: '/projects/$projectId/overview'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdOverviewRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/hse': {
      id: '/_authenticated/projects/$projectId/hse'
      path: '/hse'
      fullPath: '/projects/$projectId/hse'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdHseRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/gates': {
      id: '/_authenticated/projects/$projectId/gates'
      path: '/gates'
      fullPath: '/projects/$projectId/gates'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdGatesRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/finance': {
      id: '/_authenticated/projects/$projectId/finance'
      path: '/finance'
      fullPath: '/projects/$projectId/finance'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdFinanceRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/engineering': {
      id: '/_authenticated/projects/$projectId/engineering'
      path: '/engineering'
      fullPath: '/projects/$projectId/engineering'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEngineeringRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/construction': {
      id: '/_authenticated/projects/$projectId/construction'
      path: '/construction'
      fullPath: '/projects/$projectId/construction'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdConstructionRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/config': {
      id: '/_authenticated/projects/$projectId/config'
      path: '/config'
      fullPath: '/projects/$projectId/config'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdConfigRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/crm/opportunities/$opportunityId': {
      id: '/_authenticated/crm/opportunities/$opportunityId'
      path: '/crm/opportunities/$opportunityId'
      fullPath: '/crm/opportunities/$opportunityId'
      preLoaderRoute: typeof AuthenticatedCrmOpportunitiesOpportunityIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tenants/$companyId': {
      id: '/_authenticated/admin/tenants/$companyId'
      path: '/$companyId'
      fullPath: '/admin/tenants/$companyId'
      preLoaderRoute: typeof AuthenticatedAdminTenantsCompanyIdRouteImport
      parentRoute: typeof AuthenticatedAdminTenantsRouteRoute
    }
    '/_authenticated/projects/$projectId/engineering/': {
      id: '/_authenticated/projects/$projectId/engineering/'
      path: '/'
      fullPath: '/projects/$projectId/engineering/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEngineeringIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdEngineeringRoute
    }
    '/_authenticated/projects/$projectId/engineering/yield': {
      id: '/_authenticated/projects/$projectId/engineering/yield'
      path: '/yield'
      fullPath: '/projects/$projectId/engineering/yield'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEngineeringYieldRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdEngineeringRoute
    }
    '/_authenticated/projects/$projectId/engineering/uploads': {
      id: '/_authenticated/projects/$projectId/engineering/uploads'
      path: '/uploads'
      fullPath: '/projects/$projectId/engineering/uploads'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEngineeringUploadsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdEngineeringRoute
    }
    '/_authenticated/projects/$projectId/engineering/sld': {
      id: '/_authenticated/projects/$projectId/engineering/sld'
      path: '/sld'
      fullPath: '/projects/$projectId/engineering/sld'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEngineeringSldRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdEngineeringRoute
    }
    '/_authenticated/projects/$projectId/engineering/reviews': {
      id: '/_authenticated/projects/$projectId/engineering/reviews'
      path: '/reviews'
      fullPath: '/projects/$projectId/engineering/reviews'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEngineeringReviewsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdEngineeringRoute
    }
    '/_authenticated/projects/$projectId/engineering/drawings': {
      id: '/_authenticated/projects/$projectId/engineering/drawings'
      path: '/drawings'
      fullPath: '/projects/$projectId/engineering/drawings'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEngineeringDrawingsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdEngineeringRoute
    }
    '/_authenticated/projects/$projectId/engineering/bom': {
      id: '/_authenticated/projects/$projectId/engineering/bom'
      path: '/bom'
      fullPath: '/projects/$projectId/engineering/bom'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEngineeringBomRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdEngineeringRoute
    }
    '/_authenticated/projects/$projectId/engineering/drawings/': {
      id: '/_authenticated/projects/$projectId/engineering/drawings/'
      path: '/'
      fullPath: '/projects/$projectId/engineering/drawings/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEngineeringDrawingsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdEngineeringDrawingsRoute
    }
    '/_authenticated/projects/$projectId/engineering/drawings/$drawingId': {
      id: '/_authenticated/projects/$projectId/engineering/drawings/$drawingId'
      path: '/$drawingId'
      fullPath: '/projects/$projectId/engineering/drawings/$drawingId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEngineeringDrawingsDrawingIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdEngineeringDrawingsRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedAdminTenantsRouteRouteChildren {
  AuthenticatedAdminTenantsCompanyIdRoute: typeof AuthenticatedAdminTenantsCompanyIdRoute
  AuthenticatedAdminTenantsIndexRoute: typeof AuthenticatedAdminTenantsIndexRoute
}

const AuthenticatedAdminTenantsRouteRouteChildren: AuthenticatedAdminTenantsRouteRouteChildren =
  {
    AuthenticatedAdminTenantsCompanyIdRoute:
      AuthenticatedAdminTenantsCompanyIdRoute,
    AuthenticatedAdminTenantsIndexRoute: AuthenticatedAdminTenantsIndexRoute,
  }

const AuthenticatedAdminTenantsRouteRouteWithChildren =
  AuthenticatedAdminTenantsRouteRoute._addFileChildren(
    AuthenticatedAdminTenantsRouteRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminTenantsRouteRoute: typeof AuthenticatedAdminTenantsRouteRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminTenantsRouteRoute:
    AuthenticatedAdminTenantsRouteRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedProjectsProjectIdEngineeringDrawingsRouteChildren {
  AuthenticatedProjectsProjectIdEngineeringDrawingsDrawingIdRoute: typeof AuthenticatedProjectsProjectIdEngineeringDrawingsDrawingIdRoute
  AuthenticatedProjectsProjectIdEngineeringDrawingsIndexRoute: typeof AuthenticatedProjectsProjectIdEngineeringDrawingsIndexRoute
}

const AuthenticatedProjectsProjectIdEngineeringDrawingsRouteChildren: AuthenticatedProjectsProjectIdEngineeringDrawingsRouteChildren =
  {
    AuthenticatedProjectsProjectIdEngineeringDrawingsDrawingIdRoute:
      AuthenticatedProjectsProjectIdEngineeringDrawingsDrawingIdRoute,
    AuthenticatedProjectsProjectIdEngineeringDrawingsIndexRoute:
      AuthenticatedProjectsProjectIdEngineeringDrawingsIndexRoute,
  }

const AuthenticatedProjectsProjectIdEngineeringDrawingsRouteWithChildren =
  AuthenticatedProjectsProjectIdEngineeringDrawingsRoute._addFileChildren(
    AuthenticatedProjectsProjectIdEngineeringDrawingsRouteChildren,
  )

interface AuthenticatedProjectsProjectIdEngineeringRouteChildren {
  AuthenticatedProjectsProjectIdEngineeringBomRoute: typeof AuthenticatedProjectsProjectIdEngineeringBomRoute
  AuthenticatedProjectsProjectIdEngineeringDrawingsRoute: typeof AuthenticatedProjectsProjectIdEngineeringDrawingsRouteWithChildren
  AuthenticatedProjectsProjectIdEngineeringReviewsRoute: typeof AuthenticatedProjectsProjectIdEngineeringReviewsRoute
  AuthenticatedProjectsProjectIdEngineeringSldRoute: typeof AuthenticatedProjectsProjectIdEngineeringSldRoute
  AuthenticatedProjectsProjectIdEngineeringUploadsRoute: typeof AuthenticatedProjectsProjectIdEngineeringUploadsRoute
  AuthenticatedProjectsProjectIdEngineeringYieldRoute: typeof AuthenticatedProjectsProjectIdEngineeringYieldRoute
  AuthenticatedProjectsProjectIdEngineeringIndexRoute: typeof AuthenticatedProjectsProjectIdEngineeringIndexRoute
}

const AuthenticatedProjectsProjectIdEngineeringRouteChildren: AuthenticatedProjectsProjectIdEngineeringRouteChildren =
  {
    AuthenticatedProjectsProjectIdEngineeringBomRoute:
      AuthenticatedProjectsProjectIdEngineeringBomRoute,
    AuthenticatedProjectsProjectIdEngineeringDrawingsRoute:
      AuthenticatedProjectsProjectIdEngineeringDrawingsRouteWithChildren,
    AuthenticatedProjectsProjectIdEngineeringReviewsRoute:
      AuthenticatedProjectsProjectIdEngineeringReviewsRoute,
    AuthenticatedProjectsProjectIdEngineeringSldRoute:
      AuthenticatedProjectsProjectIdEngineeringSldRoute,
    AuthenticatedProjectsProjectIdEngineeringUploadsRoute:
      AuthenticatedProjectsProjectIdEngineeringUploadsRoute,
    AuthenticatedProjectsProjectIdEngineeringYieldRoute:
      AuthenticatedProjectsProjectIdEngineeringYieldRoute,
    AuthenticatedProjectsProjectIdEngineeringIndexRoute:
      AuthenticatedProjectsProjectIdEngineeringIndexRoute,
  }

const AuthenticatedProjectsProjectIdEngineeringRouteWithChildren =
  AuthenticatedProjectsProjectIdEngineeringRoute._addFileChildren(
    AuthenticatedProjectsProjectIdEngineeringRouteChildren,
  )

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdConfigRoute: typeof AuthenticatedProjectsProjectIdConfigRoute
  AuthenticatedProjectsProjectIdConstructionRoute: typeof AuthenticatedProjectsProjectIdConstructionRoute
  AuthenticatedProjectsProjectIdEngineeringRoute: typeof AuthenticatedProjectsProjectIdEngineeringRouteWithChildren
  AuthenticatedProjectsProjectIdFinanceRoute: typeof AuthenticatedProjectsProjectIdFinanceRoute
  AuthenticatedProjectsProjectIdGatesRoute: typeof AuthenticatedProjectsProjectIdGatesRoute
  AuthenticatedProjectsProjectIdHseRoute: typeof AuthenticatedProjectsProjectIdHseRoute
  AuthenticatedProjectsProjectIdOverviewRoute: typeof AuthenticatedProjectsProjectIdOverviewRoute
  AuthenticatedProjectsProjectIdProcurementRoute: typeof AuthenticatedProjectsProjectIdProcurementRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdConfigRoute:
      AuthenticatedProjectsProjectIdConfigRoute,
    AuthenticatedProjectsProjectIdConstructionRoute:
      AuthenticatedProjectsProjectIdConstructionRoute,
    AuthenticatedProjectsProjectIdEngineeringRoute:
      AuthenticatedProjectsProjectIdEngineeringRouteWithChildren,
    AuthenticatedProjectsProjectIdFinanceRoute:
      AuthenticatedProjectsProjectIdFinanceRoute,
    AuthenticatedProjectsProjectIdGatesRoute:
      AuthenticatedProjectsProjectIdGatesRoute,
    AuthenticatedProjectsProjectIdHseRoute:
      AuthenticatedProjectsProjectIdHseRoute,
    AuthenticatedProjectsProjectIdOverviewRoute:
      AuthenticatedProjectsProjectIdOverviewRoute,
    AuthenticatedProjectsProjectIdProcurementRoute:
      AuthenticatedProjectsProjectIdProcurementRoute,
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCrmPipelineRoute: typeof AuthenticatedCrmPipelineRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedProposalsProposalIdRoute: typeof AuthenticatedProposalsProposalIdRoute
  AuthenticatedSettingsCompanyRoute: typeof AuthenticatedSettingsCompanyRoute
  AuthenticatedSettingsDepartmentsRoute: typeof AuthenticatedSettingsDepartmentsRoute
  AuthenticatedSettingsModulesRoute: typeof AuthenticatedSettingsModulesRoute
  AuthenticatedSettingsPermissionsSimulatorRoute: typeof AuthenticatedSettingsPermissionsSimulatorRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedProposalsIndexRoute: typeof AuthenticatedProposalsIndexRoute
  AuthenticatedCrmOpportunitiesOpportunityIdRoute: typeof AuthenticatedCrmOpportunitiesOpportunityIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCrmPipelineRoute: AuthenticatedCrmPipelineRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedProposalsProposalIdRoute: AuthenticatedProposalsProposalIdRoute,
  AuthenticatedSettingsCompanyRoute: AuthenticatedSettingsCompanyRoute,
  AuthenticatedSettingsDepartmentsRoute: AuthenticatedSettingsDepartmentsRoute,
  AuthenticatedSettingsModulesRoute: AuthenticatedSettingsModulesRoute,
  AuthenticatedSettingsPermissionsSimulatorRoute:
    AuthenticatedSettingsPermissionsSimulatorRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedProposalsIndexRoute: AuthenticatedProposalsIndexRoute,
  AuthenticatedCrmOpportunitiesOpportunityIdRoute:
    AuthenticatedCrmOpportunitiesOpportunityIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  DesignSystemRoute: DesignSystemRoute,
  ApiWebhooksEsignRoute: ApiWebhooksEsignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
