-- P-139 — SLD electrical symbol registry (data-driven), plus the global seed set.

create table if not exists public.sld_symbol_types (
  id uuid primary key default gen_random_uuid(),
  company_id uuid references public.companies(id) on delete cascade, -- null = global
  type_key text not null,
  display_name text not null,
  category text not null check (category in
    ('generation','conversion','switchgear','protection','measurement',
     'distribution','cable_bus','earthing','monitoring','storage','auxiliary','grid')),
  svg_body text not null,
  ports jsonb not null default '[]',
  property_schema jsonb not null default '[]',
  default_properties jsonb not null default '{}',
  tag_prefix text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, type_key)
);

-- unique(company_id, type_key) does not constrain global rows (null company_id).
create unique index if not exists sld_symbol_types_global_key_uidx
  on public.sld_symbol_types (type_key) where company_id is null;

grant select, insert, update on public.sld_symbol_types to authenticated;
grant all on public.sld_symbol_types to service_role;

alter table public.sld_symbol_types enable row level security;
alter table public.sld_symbol_types force row level security;

drop policy if exists sld_symbol_types_select on public.sld_symbol_types;
create policy sld_symbol_types_select on public.sld_symbol_types for select to authenticated
  using (company_id is null or public.is_company_member(company_id));

drop policy if exists sld_symbol_types_write on public.sld_symbol_types;
create policy sld_symbol_types_write on public.sld_symbol_types for all to authenticated
  using (
    company_id is not null
    and public.is_company_member(company_id)
    and (public.has_company_role('engineering_admin'::app_role)
         or public.has_company_role('company_admin'::app_role))
  )
  with check (
    company_id is not null
    and public.is_company_member(company_id)
    and (public.has_company_role('engineering_admin'::app_role)
         or public.has_company_role('company_admin'::app_role))
  );

drop trigger if exists set_updated_at_sld_symbol_types on public.sld_symbol_types;
create trigger set_updated_at_sld_symbol_types
  before update on public.sld_symbol_types
  for each row execute function public.set_updated_at();

insert into public.sld_symbol_types
  (company_id, type_key, display_name, category, svg_body, ports, property_schema,
   default_properties, tag_prefix, sort_order)
values
  (null, 'pv_module', 'PV module', 'generation', '<rect x="6" y="8" width="28" height="20"/><line x1="15" y1="8" x2="15" y2="28"/><line x1="25" y1="8" x2="25" y2="28"/><line x1="6" y1="18" x2="34" y2="18"/><line x1="20" y1="34" x2="20" y2="40"/>', '[{"key": "dc_out", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "wp", "label": "Rated power", "type": "number", "unit": "Wp", "required": true}, {"key": "voc_v", "label": "Voc", "type": "number", "unit": "V"}, {"key": "isc_a", "label": "Isc", "type": "number", "unit": "A"}, {"key": "model", "label": "Model", "type": "text"}]'::jsonb, '{"wp": 610}'::jsonb, 'PV', 10),
  (null, 'pv_string', 'PV string', 'generation', '<rect x="4" y="10" width="10" height="16"/><rect x="16" y="10" width="10" height="16"/><line x1="29" y1="18" x2="35" y2="18"/><circle cx="31" cy="18" r="1.2" fill="currentColor"/><circle cx="34" cy="18" r="1.2" fill="currentColor"/><line x1="20" y1="34" x2="20" y2="40"/>', '[{"key": "dc_out", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "modules_in_series", "label": "Modules in series", "type": "number", "required": true}, {"key": "vmp_v", "label": "Vmp", "type": "number", "unit": "V"}, {"key": "imp_a", "label": "Imp", "type": "number", "unit": "A"}]'::jsonb, '{"modules_in_series": 26}'::jsonb, 'STR', 20),
  (null, 'generator', 'Diesel generator', 'generation', '<circle cx="20" cy="20" r="13"/><text x="20" y="25" text-anchor="middle" font-size="14" fill="currentColor">G</text><line x1="34" y1="20" x2="40" y2="20"/>', '[{"key": "ac_out", "x": 40, "y": 20, "side": "right"}]'::jsonb, '[{"key": "rated_kva", "label": "Rated power", "type": "number", "unit": "kVA", "required": true}, {"key": "voltage_kv", "label": "Voltage", "type": "number", "unit": "kV"}, {"key": "fuel", "label": "Fuel", "type": "select", "options": ["diesel", "gas", "hvo"]}]'::jsonb, '{}'::jsonb, 'GEN', 30),
  (null, 'inverter', 'Inverter', 'conversion', '<rect x="6" y="6" width="28" height="28" rx="2"/><line x1="12" y1="30" x2="28" y2="10"/><line x1="9" y1="14" x2="17" y2="14"/><line x1="9" y1="17" x2="17" y2="17"/><path d="M23 26 q2.5 -5 5 0"/><line x1="0" y1="20" x2="6" y2="20"/><line x1="34" y1="20" x2="40" y2="20"/>', '[{"key": "dc_in", "x": 0, "y": 20, "side": "left"}, {"key": "ac_out", "x": 40, "y": 20, "side": "right"}]'::jsonb, '[{"key": "rated_power_kw", "label": "Rated power", "type": "number", "unit": "kW", "required": true}, {"key": "max_dc_voltage_v", "label": "Max DC voltage", "type": "number", "unit": "V"}, {"key": "mppt_count", "label": "MPPT count", "type": "number"}, {"key": "efficiency_pct", "label": "Efficiency", "type": "number", "unit": "%", "min": 0, "max": 100}, {"key": "model", "label": "Model", "type": "text"}]'::jsonb, '{"mppt_count": 12}'::jsonb, 'INV', 40),
  (null, 'pcs', 'Power conversion system (PCS)', 'conversion', '<rect x="6" y="6" width="28" height="28" rx="2"/><line x1="12" y1="30" x2="28" y2="10"/><path d="M9 15 h8 M23 25 q2.5 -5 5 0"/><path d="M14 34 l6 4 l6 -4"/><line x1="0" y1="20" x2="6" y2="20"/><line x1="34" y1="20" x2="40" y2="20"/>', '[{"key": "dc_in", "x": 0, "y": 20, "side": "left"}, {"key": "ac_out", "x": 40, "y": 20, "side": "right"}]'::jsonb, '[{"key": "rated_power_kw", "label": "Rated power", "type": "number", "unit": "kW", "required": true}, {"key": "dc_voltage_range_v", "label": "DC voltage range", "type": "number", "unit": "V"}, {"key": "bidirectional", "label": "Bidirectional", "type": "bool"}, {"key": "grid_forming", "label": "Grid mode", "type": "select", "options": ["grid_following", "grid_forming"]}]'::jsonb, '{"bidirectional": true}'::jsonb, 'PCS', 50),
  (null, 'transformer', 'Power transformer', 'conversion', '<circle cx="20" cy="15" r="9"/><circle cx="20" cy="25" r="9"/><line x1="20" y1="0" x2="20" y2="6"/><line x1="20" y1="34" x2="20" y2="40"/>', '[{"key": "hv", "x": 20, "y": 0, "side": "top"}, {"key": "lv", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "rated_kva", "label": "Rated power", "type": "number", "unit": "kVA", "required": true}, {"key": "hv_kv", "label": "HV", "type": "number", "unit": "kV", "required": true}, {"key": "lv_kv", "label": "LV", "type": "number", "unit": "kV", "required": true}, {"key": "vector_group", "label": "Vector group", "type": "text"}, {"key": "impedance_pct", "label": "Impedance", "type": "number", "unit": "%"}, {"key": "cooling", "label": "Cooling", "type": "select", "options": ["ONAN", "ONAF", "KNAN", "dry"]}]'::jsonb, '{"vector_group": "Dyn11"}'::jsonb, 'XFMR', 60),
  (null, 'aux_transformer', 'Auxiliary transformer', 'conversion', '<circle cx="20" cy="15" r="8"/><circle cx="20" cy="25" r="8"/><text x="20" y="39" text-anchor="middle" font-size="7" fill="currentColor">aux</text><line x1="20" y1="0" x2="20" y2="6"/><line x1="20" y1="34" x2="20" y2="40"/>', '[{"key": "hv", "x": 20, "y": 0, "side": "top"}, {"key": "lv", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "rated_kva", "label": "Rated power", "type": "number", "unit": "kVA", "required": true}, {"key": "hv_kv", "label": "HV", "type": "number", "unit": "kV"}, {"key": "lv_kv", "label": "LV", "type": "number", "unit": "kV"}, {"key": "vector_group", "label": "Vector group", "type": "text"}]'::jsonb, '{"lv_kv": 0.4}'::jsonb, 'AUX', 70),
  (null, 'mv_switchgear', 'MV switchgear', 'switchgear', '<rect x="4" y="10" width="32" height="20"/><line x1="14" y1="10" x2="14" y2="30"/><line x1="26" y1="10" x2="26" y2="30"/><text x="20" y="25" text-anchor="middle" font-size="8" fill="currentColor">MV</text><line x1="20" y1="0" x2="20" y2="6"/><line x1="20" y1="34" x2="20" y2="40"/>', '[{"key": "in", "x": 20, "y": 0, "side": "top"}, {"key": "out", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "voltage_kv", "label": "Rated voltage", "type": "number", "unit": "kV", "required": true}, {"key": "busbar_current_a", "label": "Busbar current", "type": "number", "unit": "A"}, {"key": "short_circuit_ka", "label": "Short-circuit rating", "type": "number", "unit": "kA"}, {"key": "panel_count", "label": "Panels", "type": "number"}]'::jsonb, '{"voltage_kv": 33}'::jsonb, 'MVSG', 80),
  (null, 'lv_switchgear', 'LV switchgear', 'switchgear', '<rect x="4" y="10" width="32" height="20"/><line x1="14" y1="10" x2="14" y2="30"/><line x1="26" y1="10" x2="26" y2="30"/><text x="20" y="25" text-anchor="middle" font-size="8" fill="currentColor">LV</text><line x1="20" y1="0" x2="20" y2="6"/><line x1="20" y1="34" x2="20" y2="40"/>', '[{"key": "in", "x": 20, "y": 0, "side": "top"}, {"key": "out", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "voltage_v", "label": "Rated voltage", "type": "number", "unit": "V", "required": true}, {"key": "busbar_current_a", "label": "Busbar current", "type": "number", "unit": "A"}, {"key": "short_circuit_ka", "label": "Short-circuit rating", "type": "number", "unit": "kA"}]'::jsonb, '{"voltage_v": 400}'::jsonb, 'LVSG', 90),
  (null, 'ring_main_unit', 'Ring main unit', 'switchgear', '<rect x="5" y="12" width="30" height="16"/><circle cx="13" cy="20" r="3"/><circle cx="20" cy="20" r="3"/><circle cx="27" cy="20" r="3"/><line x1="0" y1="20" x2="6" y2="20"/><line x1="34" y1="20" x2="40" y2="20"/><line x1="20" y1="34" x2="20" y2="40"/>', '[{"key": "ring_a", "x": 0, "y": 20, "side": "left"}, {"key": "ring_b", "x": 40, "y": 20, "side": "right"}, {"key": "tee", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "voltage_kv", "label": "Rated voltage", "type": "number", "unit": "kV", "required": true}, {"key": "rated_current_a", "label": "Rated current", "type": "number", "unit": "A"}, {"key": "configuration", "label": "Configuration", "type": "select", "options": ["2S+1T", "3S+1T", "4S+2T"]}]'::jsonb, '{"voltage_kv": 33}'::jsonb, 'RMU', 100),
  (null, 'string_combiner', 'String combiner', 'switchgear', '<rect x="6" y="8" width="28" height="24" rx="2"/><line x1="0" y1="14" x2="6" y2="14"/><line x1="0" y1="20" x2="6" y2="20"/><line x1="0" y1="26" x2="6" y2="26"/><line x1="12" y1="20" x2="28" y2="20"/><line x1="34" y1="20" x2="40" y2="20"/>', '[{"key": "dc_in_1", "x": 0, "y": 14, "side": "left"}, {"key": "dc_in_2", "x": 0, "y": 20, "side": "left"}, {"key": "dc_in_3", "x": 0, "y": 26, "side": "left"}, {"key": "dc_out", "x": 40, "y": 20, "side": "right"}]'::jsonb, '[{"key": "input_count", "label": "String inputs", "type": "number", "required": true}, {"key": "fuse_rating_a", "label": "Fuse rating", "type": "number", "unit": "A"}, {"key": "max_dc_voltage_v", "label": "Max DC voltage", "type": "number", "unit": "V"}, {"key": "monitored", "label": "String monitoring", "type": "bool"}]'::jsonb, '{"input_count": 16}'::jsonb, 'SCB', 110),
  (null, 'dc_combiner_box', 'DC combiner box', 'switchgear', '<rect x="6" y="8" width="28" height="24" rx="2"/><text x="20" y="23" text-anchor="middle" font-size="10" fill="currentColor">DC</text><line x1="0" y1="16" x2="6" y2="16"/><line x1="0" y1="24" x2="6" y2="24"/><line x1="34" y1="20" x2="40" y2="20"/>', '[{"key": "dc_in_1", "x": 0, "y": 16, "side": "left"}, {"key": "dc_in_2", "x": 0, "y": 24, "side": "left"}, {"key": "dc_out", "x": 40, "y": 20, "side": "right"}]'::jsonb, '[{"key": "input_count", "label": "Inputs", "type": "number", "required": true}, {"key": "rated_current_a", "label": "Rated current", "type": "number", "unit": "A"}, {"key": "spd_fitted", "label": "SPD fitted", "type": "bool"}]'::jsonb, '{"input_count": 8}'::jsonb, 'DCB', 120),
  (null, 'circuit_breaker', 'Circuit breaker', 'protection', '<line x1="20" y1="0" x2="20" y2="6"/><line x1="20" y1="6" x2="20" y2="13"/><rect x="14" y="13" width="12" height="14"/><line x1="14" y1="13" x2="26" y2="27"/><line x1="20" y1="27" x2="20" y2="34"/><line x1="20" y1="34" x2="20" y2="40"/>', '[{"key": "in", "x": 20, "y": 0, "side": "top"}, {"key": "out", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "rated_current_a", "label": "Rated current", "type": "number", "unit": "A", "required": true}, {"key": "breaking_ka", "label": "Breaking capacity", "type": "number", "unit": "kA", "required": true}, {"key": "voltage_kv", "label": "Rated voltage", "type": "number", "unit": "kV"}, {"key": "type", "label": "Type", "type": "select", "options": ["vacuum", "SF6", "air", "moulded_case"]}]'::jsonb, '{}'::jsonb, 'CB', 130),
  (null, 'disconnector', 'Disconnector', 'protection', '<line x1="20" y1="0" x2="20" y2="6"/><line x1="20" y1="6" x2="20" y2="14"/><circle cx="20" cy="14" r="1.6" fill="currentColor"/><line x1="20" y1="14" x2="29" y2="26"/><circle cx="20" cy="27" r="1.6" fill="currentColor"/><line x1="20" y1="27" x2="20" y2="34"/><line x1="20" y1="34" x2="20" y2="40"/>', '[{"key": "in", "x": 20, "y": 0, "side": "top"}, {"key": "out", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "rated_current_a", "label": "Rated current", "type": "number", "unit": "A", "required": true}, {"key": "voltage_kv", "label": "Rated voltage", "type": "number", "unit": "kV"}, {"key": "earthing_switch", "label": "Integrated earthing switch", "type": "bool"}, {"key": "motorised", "label": "Motorised", "type": "bool"}]'::jsonb, '{}'::jsonb, 'DS', 140),
  (null, 'fuse', 'Fuse', 'protection', '<line x1="20" y1="0" x2="20" y2="6"/><rect x="15" y="10" width="10" height="20"/><line x1="20" y1="10" x2="20" y2="30"/><line x1="20" y1="34" x2="20" y2="40"/>', '[{"key": "in", "x": 20, "y": 0, "side": "top"}, {"key": "out", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "rated_current_a", "label": "Rated current", "type": "number", "unit": "A", "required": true}, {"key": "breaking_ka", "label": "Breaking capacity", "type": "number", "unit": "kA"}, {"key": "class", "label": "Class", "type": "select", "options": ["gG", "aM", "gPV", "NH"]}]'::jsonb, '{}'::jsonb, 'FU', 150),
  (null, 'protection_relay', 'Protection relay', 'protection', '<rect x="7" y="10" width="26" height="20"/><text x="20" y="25" text-anchor="middle" font-size="12" fill="currentColor">I&gt;</text><line x1="0" y1="20" x2="6" y2="20"/><line x1="34" y1="20" x2="40" y2="20"/>', '[{"key": "ct_in", "x": 0, "y": 20, "side": "left"}, {"key": "trip_out", "x": 40, "y": 20, "side": "right"}]'::jsonb, '[{"key": "ansi_functions", "label": "ANSI functions", "type": "text", "required": true}, {"key": "model", "label": "Model", "type": "text"}, {"key": "protocol", "label": "Station protocol", "type": "select", "options": ["IEC 61850", "Modbus TCP", "DNP3", "none"]}]'::jsonb, '{"ansi_functions": "50/51, 27/59, 81"}'::jsonb, 'RLY', 160),
  (null, 'spd', 'Surge arrester (SPD)', 'protection', '<line x1="20" y1="0" x2="20" y2="6"/><rect x="14" y="10" width="12" height="16"/><path d="M17 13 l6 5 l-6 5"/><line x1="20" y1="26" x2="20" y2="32"/><line x1="13" y1="32" x2="27" y2="32"/><line x1="16" y1="35" x2="24" y2="35"/>', '[{"key": "line", "x": 20, "y": 0, "side": "top"}, {"key": "earth", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "spd_type", "label": "Type", "type": "select", "options": ["Type 1", "Type 2", "Type 1+2", "Type 3"], "required": true}, {"key": "uc_v", "label": "Uc", "type": "number", "unit": "V"}, {"key": "iimp_ka", "label": "Iimp", "type": "number", "unit": "kA"}]'::jsonb, '{}'::jsonb, 'SPD', 170),
  (null, 'ct', 'Current transformer', 'measurement', '<line x1="20" y1="0" x2="20" y2="6"/><line x1="20" y1="0" x2="20" y2="40"/><circle cx="26" cy="20" r="6"/><line x1="20" y1="34" x2="20" y2="40"/>', '[{"key": "primary_in", "x": 20, "y": 0, "side": "top"}, {"key": "primary_out", "x": 20, "y": 40, "side": "bottom"}, {"key": "secondary", "x": 40, "y": 20, "side": "right"}]'::jsonb, '[{"key": "ratio", "label": "Ratio", "type": "text", "required": true}, {"key": "accuracy_class", "label": "Accuracy class", "type": "select", "options": ["0.2S", "0.5", "1.0", "5P20", "10P10"]}, {"key": "burden_va", "label": "Burden", "type": "number", "unit": "VA"}]'::jsonb, '{"ratio": "400/5"}'::jsonb, 'CT', 180),
  (null, 'vt', 'Voltage transformer', 'measurement', '<line x1="20" y1="0" x2="20" y2="6"/><line x1="20" y1="0" x2="20" y2="12"/><circle cx="20" cy="18" r="6"/><circle cx="20" cy="27" r="6"/><line x1="34" y1="20" x2="40" y2="20"/>', '[{"key": "primary", "x": 20, "y": 0, "side": "top"}, {"key": "secondary", "x": 40, "y": 20, "side": "right"}]'::jsonb, '[{"key": "ratio", "label": "Ratio", "type": "text", "required": true}, {"key": "accuracy_class", "label": "Accuracy class", "type": "select", "options": ["0.2", "0.5", "1.0", "3P", "6P"]}, {"key": "burden_va", "label": "Burden", "type": "number", "unit": "VA"}]'::jsonb, '{"ratio": "33000/110"}'::jsonb, 'VT', 190),
  (null, 'revenue_meter', 'Revenue meter', 'measurement', '<circle cx="20" cy="20" r="12"/><text x="20" y="24" text-anchor="middle" font-size="9" fill="currentColor">kWh</text><line x1="20" y1="0" x2="20" y2="6"/><line x1="20" y1="34" x2="20" y2="40"/>', '[{"key": "in", "x": 20, "y": 0, "side": "top"}, {"key": "out", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "accuracy_class", "label": "Accuracy class", "type": "select", "options": ["0.2S", "0.5S", "1.0"], "required": true}, {"key": "bidirectional", "label": "Import/export", "type": "bool"}, {"key": "owner", "label": "Metering owner", "type": "text"}]'::jsonb, '{"bidirectional": true}'::jsonb, 'MTR', 200),
  (null, 'busbar', 'Busbar', 'distribution', '<line x1="2" y1="20" x2="38" y2="20"/><line x1="12" y1="14" x2="12" y2="20"/><line x1="28" y1="20" x2="28" y2="26"/>', '[{"key": "tap_a", "x": 2, "y": 20, "side": "left"}, {"key": "tap_b", "x": 38, "y": 20, "side": "right"}, {"key": "tap_top", "x": 20, "y": 14, "side": "top"}, {"key": "tap_bottom", "x": 20, "y": 26, "side": "bottom"}]'::jsonb, '[{"key": "rated_current_a", "label": "Rated current", "type": "number", "unit": "A", "required": true}, {"key": "voltage_kv", "label": "Voltage", "type": "number", "unit": "kV"}, {"key": "material", "label": "Material", "type": "select", "options": ["copper", "aluminium"]}, {"key": "short_time_ka", "label": "Short-time current", "type": "number", "unit": "kA"}]'::jsonb, '{}'::jsonb, 'BB', 210),
  (null, 'cable', 'Cable', 'cable_bus', '<line x1="2" y1="20" x2="38" y2="20"/><line x1="14" y1="15" x2="18" y2="25"/><line x1="22" y1="15" x2="26" y2="25"/>', '[{"key": "a", "x": 2, "y": 20, "side": "left"}, {"key": "b", "x": 38, "y": 20, "side": "right"}]'::jsonb, '[{"key": "size_mm2", "label": "Conductor size", "type": "number", "unit": "mm²", "required": true}, {"key": "length_m", "label": "Length", "type": "number", "unit": "m", "required": true}, {"key": "voltage_kv", "label": "Voltage rating", "type": "number", "unit": "kV", "required": true}, {"key": "conductor", "label": "Conductor", "type": "select", "options": ["copper", "aluminium"]}, {"key": "cores", "label": "Cores", "type": "number"}, {"key": "installation", "label": "Installation", "type": "select", "options": ["buried", "tray", "duct", "overhead"]}]'::jsonb, '{"conductor": "aluminium", "cores": 3}'::jsonb, 'CBL', 220),
  (null, 'earthing', 'Earthing', 'earthing', '<line x1="20" y1="0" x2="20" y2="6"/><line x1="20" y1="0" x2="20" y2="22"/><line x1="8" y1="22" x2="32" y2="22"/><line x1="12" y1="27" x2="28" y2="27"/><line x1="16" y1="32" x2="24" y2="32"/>', '[{"key": "earth", "x": 20, "y": 0, "side": "top"}]'::jsonb, '[{"key": "earthing_type", "label": "Type", "type": "select", "options": ["solid", "resistance", "reactance", "unearthed"], "required": true}, {"key": "resistance_ohm", "label": "Resistance", "type": "number", "unit": "Ω"}, {"key": "electrode_count", "label": "Electrodes", "type": "number"}]'::jsonb, '{"earthing_type": "solid"}'::jsonb, 'EARTH', 230),
  (null, 'capacitor_bank', 'Capacitor bank', 'distribution', '<line x1="20" y1="0" x2="20" y2="6"/><line x1="20" y1="0" x2="20" y2="17"/><line x1="10" y1="17" x2="30" y2="17"/><line x1="10" y1="23" x2="30" y2="23"/><line x1="20" y1="23" x2="20" y2="40"/>', '[{"key": "in", "x": 20, "y": 0, "side": "top"}, {"key": "out", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "rated_kvar", "label": "Rated reactive power", "type": "number", "unit": "kVAr", "required": true}, {"key": "voltage_kv", "label": "Voltage", "type": "number", "unit": "kV"}, {"key": "step_count", "label": "Steps", "type": "number"}, {"key": "detuned", "label": "Detuned", "type": "bool"}]'::jsonb, '{}'::jsonb, 'CAP', 240),
  (null, 'reactor', 'Reactor', 'distribution', '<line x1="20" y1="0" x2="20" y2="6"/><line x1="20" y1="0" x2="20" y2="12"/><path d="M20 12 a4 4 0 1 1 0 8 a4 4 0 1 1 0 8"/><line x1="20" y1="28" x2="20" y2="40"/>', '[{"key": "in", "x": 20, "y": 0, "side": "top"}, {"key": "out", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "inductance_mh", "label": "Inductance", "type": "number", "unit": "mH", "required": true}, {"key": "rated_current_a", "label": "Rated current", "type": "number", "unit": "A"}, {"key": "purpose", "label": "Purpose", "type": "select", "options": ["current_limiting", "harmonic", "shunt", "neutral_earthing"]}]'::jsonb, '{}'::jsonb, 'REA', 250),
  (null, 'harmonic_filter', 'Harmonic filter', 'distribution', '<line x1="20" y1="0" x2="20" y2="6"/><line x1="20" y1="0" x2="20" y2="9"/><path d="M20 9 a3 3 0 1 1 0 6 a3 3 0 1 1 0 6"/><line x1="12" y1="24" x2="28" y2="24"/><line x1="12" y1="29" x2="28" y2="29"/><line x1="20" y1="29" x2="20" y2="40"/>', '[{"key": "in", "x": 20, "y": 0, "side": "top"}, {"key": "out", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "filter_type", "label": "Filter type", "type": "select", "options": ["passive", "active", "hybrid"], "required": true}, {"key": "tuned_harmonic", "label": "Tuned harmonic order", "type": "number"}, {"key": "rated_kvar", "label": "Rated power", "type": "number", "unit": "kVAr"}]'::jsonb, '{}'::jsonb, 'HF', 260),
  (null, 'bess_rack', 'BESS rack', 'storage', '<rect x="8" y="6" width="24" height="28" rx="2"/><line x1="8" y1="15" x2="32" y2="15"/><line x1="8" y1="24" x2="32" y2="24"/><text x="20" y="13" text-anchor="middle" font-size="10" fill="currentColor">+</text><line x1="34" y1="20" x2="40" y2="20"/>', '[{"key": "dc_out", "x": 40, "y": 20, "side": "right"}]'::jsonb, '[{"key": "energy_kwh", "label": "Energy", "type": "number", "unit": "kWh", "required": true}, {"key": "power_kw", "label": "Power", "type": "number", "unit": "kW", "required": true}, {"key": "nominal_voltage_v", "label": "Nominal voltage", "type": "number", "unit": "V"}, {"key": "chemistry", "label": "Chemistry", "type": "select", "options": ["LFP", "NMC", "LTO"]}]'::jsonb, '{"chemistry": "LFP"}'::jsonb, 'BESS', 270),
  (null, 'battery_container', 'Battery container', 'storage', '<rect x="3" y="12" width="34" height="18" rx="1.5"/><line x1="12" y1="12" x2="12" y2="30"/><line x1="21" y1="12" x2="21" y2="30"/><line x1="30" y1="12" x2="30" y2="30"/><line x1="34" y1="20" x2="40" y2="20"/>', '[{"key": "dc_out", "x": 40, "y": 20, "side": "right"}, {"key": "aux", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "energy_kwh", "label": "Energy", "type": "number", "unit": "kWh", "required": true}, {"key": "power_kw", "label": "Power", "type": "number", "unit": "kW", "required": true}, {"key": "rack_count", "label": "Racks", "type": "number"}, {"key": "cooling", "label": "Cooling", "type": "select", "options": ["liquid", "air"]}, {"key": "fire_system", "label": "Fire system", "type": "select", "options": ["aerosol", "water_mist", "novec", "none"]}]'::jsonb, '{"cooling": "liquid"}'::jsonb, 'BESSC', 280),
  (null, 'ups', 'UPS', 'storage', '<rect x="6" y="6" width="28" height="28" rx="2"/><text x="20" y="24" text-anchor="middle" font-size="10" fill="currentColor">UPS</text><line x1="0" y1="20" x2="6" y2="20"/><line x1="34" y1="20" x2="40" y2="20"/>', '[{"key": "ac_in", "x": 0, "y": 20, "side": "left"}, {"key": "ac_out", "x": 40, "y": 20, "side": "right"}]'::jsonb, '[{"key": "rated_kva", "label": "Rated power", "type": "number", "unit": "kVA", "required": true}, {"key": "autonomy_min", "label": "Autonomy", "type": "number", "unit": "min"}, {"key": "topology", "label": "Topology", "type": "select", "options": ["online", "line_interactive", "offline"]}]'::jsonb, '{"topology": "online"}'::jsonb, 'UPS', 290),
  (null, 'scada_gateway', 'SCADA gateway', 'monitoring', '<rect x="6" y="12" width="28" height="16" rx="2"/><circle cx="12" cy="20" r="1.5" fill="currentColor"/><circle cx="17" cy="20" r="1.5" fill="currentColor"/><path d="M24 24 a6 6 0 0 1 6 -6"/><path d="M24 28 a10 10 0 0 1 10 -10"/><line x1="0" y1="20" x2="6" y2="20"/>', '[{"key": "field", "x": 0, "y": 20, "side": "left"}, {"key": "uplink", "x": 40, "y": 20, "side": "right"}]'::jsonb, '[{"key": "protocol", "label": "Protocol", "type": "select", "options": ["Modbus TCP", "IEC 61850", "DNP3", "OPC UA"], "required": true}, {"key": "ip_address", "label": "IP address", "type": "text"}, {"key": "redundant", "label": "Redundant pair", "type": "bool"}]'::jsonb, '{}'::jsonb, 'GW', 300),
  (null, 'data_logger', 'Data logger', 'monitoring', '<rect x="8" y="10" width="24" height="20" rx="2"/><line x1="12" y1="24" x2="12" y2="18"/><line x1="17" y1="24" x2="17" y2="15"/><line x1="22" y1="24" x2="22" y2="19"/><line x1="27" y1="24" x2="27" y2="14"/><line x1="0" y1="20" x2="6" y2="20"/>', '[{"key": "sensor_in", "x": 0, "y": 20, "side": "left"}, {"key": "data_out", "x": 40, "y": 20, "side": "right"}]'::jsonb, '[{"key": "channel_count", "label": "Channels", "type": "number"}, {"key": "interval_s", "label": "Logging interval", "type": "number", "unit": "s"}, {"key": "model", "label": "Model", "type": "text"}]'::jsonb, '{"interval_s": 60}'::jsonb, 'DL', 310),
  (null, 'weather_station', 'Weather station', 'monitoring', '<line x1="20" y1="16" x2="20" y2="36"/><line x1="14" y1="36" x2="26" y2="36"/><circle cx="20" cy="10" r="4"/><line x1="10" y1="16" x2="30" y2="16"/><circle cx="10" cy="16" r="2"/><circle cx="30" cy="16" r="2"/>', '[{"key": "data_out", "x": 40, "y": 20, "side": "right"}]'::jsonb, '[{"key": "sensor_count", "label": "Sensors", "type": "number"}, {"key": "poa_irradiance", "label": "POA irradiance", "type": "bool"}, {"key": "module_temp", "label": "Module temperature", "type": "bool"}, {"key": "wind", "label": "Wind speed / direction", "type": "bool"}]'::jsonb, '{"poa_irradiance": true}'::jsonb, 'WS', 320),
  (null, 'ems', 'Energy management system', 'monitoring', '<rect x="5" y="10" width="30" height="20" rx="2"/><text x="20" y="24" text-anchor="middle" font-size="10" fill="currentColor">EMS</text><line x1="0" y1="20" x2="6" y2="20"/><line x1="34" y1="20" x2="40" y2="20"/>', '[{"key": "control_in", "x": 0, "y": 20, "side": "left"}, {"key": "control_out", "x": 40, "y": 20, "side": "right"}]'::jsonb, '[{"key": "mode", "label": "Control mode", "type": "select", "options": ["peak_shaving", "frequency_response", "arbitrage", "self_consumption"], "required": true}, {"key": "dispatch_interval_s", "label": "Dispatch interval", "type": "number", "unit": "s"}, {"key": "poi_control", "label": "POI control", "type": "bool"}]'::jsonb, '{"dispatch_interval_s": 1}'::jsonb, 'EMS', 330),
  (null, 'grid_connection_point', 'Grid connection point', 'grid', '<circle cx="20" cy="20" r="11"/><path d="M13 20 q3.5 -6 7 0 q3.5 6 7 0"/><line x1="20" y1="0" x2="20" y2="6"/>', '[{"key": "grid", "x": 20, "y": 0, "side": "top"}, {"key": "plant", "x": 20, "y": 40, "side": "bottom"}]'::jsonb, '[{"key": "voltage_kv", "label": "Voltage", "type": "number", "unit": "kV", "required": true}, {"key": "export_capacity_mw", "label": "Export capacity", "type": "number", "unit": "MW", "required": true}, {"key": "import_capacity_mw", "label": "Import capacity", "type": "number", "unit": "MW"}, {"key": "utility", "label": "Utility / DNO", "type": "text"}, {"key": "short_circuit_mva", "label": "Grid short-circuit level", "type": "number", "unit": "MVA"}]'::jsonb, '{}'::jsonb, 'POI', 340)
on conflict do nothing;